### ISSUE TITLE
Master fails "81-test_cmp.cli.t"

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#12156]
MacOS Catalina 10.15.5, Xcode-11.5, current master.
```
Test Summary Report
-------------------
81-test_cmp_cli.t                (Wstat: 1280 Tests: 7 Failed: 5)
  Failed tests:  3-7
  Non-zero exit status: 5
Files=201, Tests=2016, 411 wallclock secs ( 5.20 usr  0.72 sys + 274.57 cusr 76.51 csys = 357.00 CPU)
Result: FAIL
```
Complete output of `make test TESTS=test_cmp_cli V=1": [81-out.txt](https://github.com/openssl/openssl/files/4780824/81-out.txt)

```
$ perl configdata.pm --dump

Command line (with current working directory = .):

    /opt/local/bin/perl5.28 ./Configure darwin64-x86_64-cc --prefix=/Users/ur20980/openssl-3 --debug --openssldir=/Users/ur20980/openssl-3/etc --with-rand-seed=rdcpu,os enable-ec_nistp_64_gcc_128 enable-md2 enable-rc5 enable-weak-ssl-ciphers zlib-dynamic enable-ssl-trace enable-trace threads enable-buildtest-c++

Perl information:

    /opt/local/bin/perl5.28
    5.28.3 for darwin-thread-multi-2level

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    buildtest-c++
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    ec_nistp_64_gcc_128
    engine
    err
    filenames
    fips
    gost
    idea
    legacy
    makedepend
    md2
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    padlockeng
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rc5
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    ssl-trace
    static-engine
    stdio
    tests
    threads
    tls
    trace
    ts
    ui-console
    whirlpool
    weak-ssl-ciphers
    zlib
    zlib-dynamic
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng            [not-linux]      OPENSSL_NO_AFALGENG
    asan                [default]        OPENSSL_NO_ASAN
    crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]        OPENSSL_NO_DEVCRYPTOENG
    egd                 [default]        OPENSSL_NO_EGD
    external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL
    ktls                [default]        OPENSSL_NO_KTLS
    msan                [default]        OPENSSL_NO_MSAN
    sctp                [default]        OPENSSL_NO_SCTP
    ubsan               [default]        OPENSSL_NO_UBSAN
    unit-test           [default]        OPENSSL_NO_UNIT_TEST
    uplink              [no uplink_arch] OPENSSL_NO_UPLINK
    ssl3                [default]        OPENSSL_NO_SSL3
    ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "r",
    CC => "cc",
    CFLAGS => "-g -O0 -Wall",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib -c",
    RC => "windres",
    asm_arch => "x86_64",
    bn_ops => "SIXTY_FOUR_BIT_LONG",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-arch x86_64",
    cppflags => "-D_REENTRANT",
    defines => [ "OPENSSL_BUILDING_OPENSSL", "ZLIB", "ZLIB_SHARED" ],
    disable => [  ],
    dso_scheme => "dlfcn",
    enable => [  ],
    includes => [  ],
    lflags => "-Wl,-search_paths_first",
    lib_cflags => "",
    lib_cppflags => "-DL_ENDIAN",
    lib_defines => [  ],
    module_cflags => "-fPIC",
    module_cxxflags => undef,
    module_ldflags => "-bundle",
    perl_platform => "Unix",
    perlasm_scheme => "macosx",
    shared_cflag => "-fPIC",
    shared_defines => [  ],
    shared_extension => ".\$(SHLIB_VERSION_NUMBER).dylib",
    shared_ldflag => "-dynamiclib -current_version \$(SHLIB_VERSION_NUMBER) -compatibility_version \$(SHLIB_VERSION_NUMBER)",
    shared_rcflag => "",
    shared_sonameflag => "-install_name \$(INSTALLTOP)/\$(LIBDIR)/",
    shared_target => "darwin-shared",
    sys_id => "MACOSX",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",

Recorded environment:

    AR = 
    ARFLAGS = 
    AS = 
    ASFLAGS = 
    BUILDFILE = 
    CC = clang
    CFLAGS = -Os -Ofast -std=gnu17 -march=native -g
    CPP = 
    CPPDEFINES = 
    CPPFLAGS = 
    CPPINCLUDES = 
    CROSS_COMPILE = 
    CXX = clang++
    CXXFLAGS = -std=gnu++17 -Os -Ofast -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
    HASHBANGPERL = 
    LD = 
    LDFLAGS = 
    LDLIBS = 
    MT = 
    MTFLAGS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    RM = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = ar
    ARFLAGS         = r
    CC              = clang
    CFLAGS          = -Os -Ofast -std=gnu17 -march=native -g
    CPPDEFINES      = 
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXX             = clang++
    CXXFLAGS        = -std=gnu++17 -Os -Ofast -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = /opt/local/bin/perl5.28
    RANLIB          = ranlib -c
    RC              = windres
    RCFLAGS         = 

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl
$ 
```

**Comment by kroeckx** [comment]
Looks like #12145, but different tests failing

**Comment by mouse07410** [comment]
In my case, tests 3-7 are failing. In #12145, test 6 succeeds - the rest of the tests behave the same way.

**Comment by DDvO** [comment]
Fixed by #12175.

**Comment by DDvO** [comment]
@mouse07410, according to the output:
```
# OPENSSL_FUNC:apps/cmp.c:2112:CMP info: will contact http://127.0.0.1:1700/pkix/ via llproxy.llan.ll.mit.edu:8080
# parse_http_line1:crypto/http/http_client.c:390:CMP error: received error : Code=502,Reason=cannotconnect
```
your proxy setup blocked connections to `127.0.0.1` (localhost).
I meanwhile override this by `-no_proxy 127.0.0.1` in case the addressed host is `127.0.0.1`.

**Comment by mouse07410** [comment]
I confirm that #12175 fixes this. @DDvO thank you!

**Comment by mouse07410** [comment]
@DDvO The proposed PR #12175 did fix this issue. The current master, however, still fails one test:
```
Test Summary Report
-------------------
81-test_cmp_cli.t                (Wstat: 256 Tests: 7 Failed: 1)
  Failed test:  7
  Non-zero exit status: 1
Files=203, Tests=2022, 408 wallclock secs ( 4.77 usr  0.76 sys + 268.05 cusr 78.63 csys = 352.21 CPU)
Result: FAIL
```

Complete log: [81-out.txt](https://github.com/openssl/openssl/files/4815192/81-out.txt)

**Comment by DDvO** [comment]
> The current master, however, still fails one test:

@mouse07410, are you sure you are the current master (i.e., at the moment commit 1d78129dd205e3e85083a91c33540a70c51b0a23)?

I'm pretty sure that #12175 did fix the issue you are referring to, and with the current master
```
make test TESTS="test_cmp_cli" VFO=1
```
succeeds for me.

**Comment by mouse07410** [comment]
> @mouse07410, are you sure you are the current master...?

Yes, I'm positive.

> I'm pretty sure that #12175 did fix the issue you are referring to...

As I said - it did fix it for me when I merged it into my clone, but then when it was merged into the master it failed one test. I suspect incomplete/incorrect merge.

> ...succeeds for me

Can it be the firewall/proxy issue? Failures appear on the firewalled machines.

**Comment by DDvO** [comment]
> but then when it was merged into the master it failed one test. I suspect incomplete/incorrect merge.

Hmm... according to the log you provided, this is the output of the failed test:
```
OPENSSL_FUNC:apps/cmp.c:1886:CMP error: could to set requested cert validity period
OPENSSL_FUNC:apps/cmp.c:3055:CMP error: cannot set up CMP context
# OPENSSL_FUNC:apps/cmp.c:2895:CMP info: using OpenSSL configuration file '../Mock/test.cnf'
# OPENSSL_FUNC:apps/cmp.c:2112:CMP info: will contact http://127.0.0.1:1700/pkix/ via llproxy.llan.ll.mit.edu:8080
# OSSL_CMP_CTX_set_option:crypto/cmp/cmp_ctx.c:945:CMP error: value too large
../../../../util/wrap.pl ../../../../apps/openssl cmp -config ../Mock/test.cnf -section 'Mock enrollment' -proxy 'llproxy.llan.ll.mit.edu:8080' -no_proxy 127.0.0.1 -cmd ir -newkey new.key -newkeypass 'pass:' -days 36500 -certout test.cert.pem -out_trusted root.crt => 1
    not ok 23 - days 365*100 beyond 2038
```
The output includes the line
```
# OSSL_CMP_CTX_set_option:crypto/cmp/cmp_ctx.c:945:CMP error: value too large
```
but this cannot happen any more with the current master since I removed that respective check (because meanwhile I included a better solution that also works beyond 2038).

Which the HEAD commit you used for testing?
If your copy of `crypto/cmp/cmp_ctx.c` still contains
```
        if (val >= (LONG_MAX - (long)time(NULL)) / (60 * 60 * 24)) {
            CMPerr(0, CMP_R_VALUE_TOO_LARGE);
            return 0;
        }
```
then for some reason you are using an outdated version,
which in my view of the universe is history.

> Can it be the firewall/proxy issue? Failures appear on the firewalled machines.

No, because when that error happens the server has not yet been contacted.

**Comment by DDvO** [comment]
@mouse07410, another indication that the tests on the current master are actually fine is that later PRs, such as #12231, which is based on commit b0d5c1cb0773588dca69875e122fac75252ccdf6, don't exhibit the issue you reported.

**Comment by mouse07410** [comment]
> If your copy of `crypto/cmp/cmp_ctx.c` still contains...

Is this what you mean?

![Screen Shot 2020-06-23 at 10 47 04](https://user-images.githubusercontent.com/5923577/85418635-03d3ca00-b53f-11ea-811c-66860bb6a346.png)

**Comment by mouse07410** [comment]
Must be a merge problem. Possibly, merging OpenSSL master into a clone that already had #12175 applied...

**Comment by mouse07410** [comment]
Pulling `crypto/cmp/cmp_ctx.c` from the GitHub seemed to fix this...
