### ISSUE TITLE
aix64-cc or aix64-gcc with asm target: make test fails (provider loading from shared modules fails)

### ISSUE THREAD

**Issue by gv74** [openssl/openssl#13336]
```
$ make teste
....
20-test_app.t ...................... ok

Verified OK
../../util/wrap.pl ../../apps/openssl dgst -sha256 -verify DSA.nonfips.priv.pem -signature DSA.nonfips.sig ../../providers/fips.so => 0
    not ok 13 - DSA: Verify something with a non-FIPS key (should fail) # TODO see issues #12626, #12627
# ------------------------------------------------------------------------------20-test_cli_fips.t ................. ok
20-test_dgst.t ..................... ok

aes-128-cbc: unable to load provider legacy
00000001:error::DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(../../providers/legacy.so): rtld: 0712-001 Symbol sha256_block_p8 was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol sha256_block_ppc../../providers/legacy.so was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol sha512_block_p8 was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol sha512_block_ppc../../providers/legacy.so was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol ChaCha20_ctr32_vmx was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol ChaCha20_ctr32_vsx was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol ChaCha20_ctr32_int was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
Additional errors occurred but are not reported.
00000001:error::DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:
00000001:error::common libcrypto routines:provider_activate:init fail:crypto/provider_core.c:537:
../../util/wrap.pl ../../apps/openssl aes-128-cbc -bufsize 113 -e -k test -provider-path ../../providers -provider default -provider legacy -in ./p -out ./p.aes-128-cbc.cipher => 1
not ok 3 - aes-128-cbc
..
<more errors here>
...
30-test_engine.t ................... ok

    # ERROR:  @ test/evp_test.c:3601
    # Failed to load config ../../test/default-and-legacy.cnf
    # 
    # 
    # Usage: evp_test [options] [file...]
    # Valid options are:
    #  -help           Display this summary
    #  -list           Display the list of tests available
    #  -test val       Run a single test by id or name
    #  -iter int       Run a single iteration of a test
    #  -indent +int    Number of tabs added to output
    #  -seed int       Seed value to randomize tests with
    #  -config infile  The configuration file to use for the libctx
    # file	File to run tests on.
../../util/wrap.pl ../../test/evp_test -config ../../test/default-and-legacy.cnf ../../test/recipes/30-test_evp_data/evpciph_aes_ccm_cavs.txt => 1
not ok 2 - running evp_test -config ../../test/default-and-legacy.cnf evpciph_aes_ccm_cavs.txt
# ------------------------------------------------------------------------------
..
<more errors here>
...

$ dump -Tv -X64 legacy.so
...
[111]   0x00000000    undef      IMP     DS EXTref libpthreads.a(shr_xpg5_64.o) pthread_rwlock_destroy
[112]   0x200058d0    .data      EXP     DS   Ldef        [noIMid] OSSL_provider_init
[113]   0x00000000    undef      IMP     DS EXTref              .. sha256_block_p8
[114]   0x00000000    undef      IMP     DS EXTref              .. sha256_block_ppc
[115]   0x00000000    undef      IMP     DS EXTref              .. sha512_block_p8
[116]   0x00000000    undef      IMP     DS EXTref              .. sha512_block_ppc
[117]   0x00000000    undef      IMP     DS EXTref              .. ChaCha20_ctr32_vmx
[118]   0x00000000    undef      IMP     DS EXTref              .. ChaCha20_ctr32_vsx
[119]   0x00000000    undef      IMP     DS EXTref              .. ChaCha20_ctr32_int
[120]   0x00000000    undef      IMP     DS EXTref              .. poly1305_init_int
[121]   0x00000000    undef      IMP     DS EXTref              .. poly1305_blocks_vsx
[122]   0x00000000    undef      IMP     DS EXTref              .. poly1305_emit
[123]   0x00000000    undef      IMP     DS EXTref              .. poly1305_blocks
```

**Comment by gv74** [comment]
tests.log

**Comment by gv74** [comment]
[tests.log.gz](https://github.com/openssl/openssl/files/5502020/tests.log.gz)
tests.log file.

**Comment by gv74** [comment]
The configure command is:
./Configure --prefix=/usr/pd --libdir=lib64 --openssldir=/var/pd/ssl enable-camellia enable-seed aix64-gcc -pipe -Wall -grecord-gcc-switches

**Comment by gv74** [comment]
Also, if I choose not to build the legacy provider (no-legacy) the legacy tests are still executed.

**Comment by levitte** [comment]
@makr, are you around and can help figure this one out?

**Comment by makr** [comment]
I am overloaded currently with private and business stuff. I'll try to find some time. Could you, @gv74 , meanwhile please comment on the version of AIX you are using?

**Comment by gv74** [comment]
$ oslevel -s
7100-05-05-1939

**Comment by makr** [comment]
Hm ... I tried ...-alpha9 with xlC 13.1.3 as usual (I don't have gcc on these machines). I chose a shorter configuration in order to just make a test drive: ```./Configure --prefix=/some/where aix64-cc```
The machine is very busy, hence it will probably need some time until it finishes with the tests. But I can report already that the above mentioned test cases were all reported as ok.
@gv74 could you just do another build on your machine and see if this goes through? Please strip your Configure-line down to ```./Configure --prefix=/usr/pd --openssldir=/var/pd/ssl aix64-gcc``` then ```gmake && gmake test```.
I have not found the time to actually look into the sources, but I have a certain feeling that the ```--libdir``` is causing a change that might mean nothing on AIX.

**Comment by gv74** [comment]
[openssl-3.0.0-alpha9-configure.log.gz](https://github.com/openssl/openssl/files/5700965/openssl-3.0.0-alpha9-configure.log.gz)

**Comment by gv74** [comment]
[openssl-3.0.0-alpha9-build.log.gz](https://github.com/openssl/openssl/files/5700969/openssl-3.0.0-alpha9-build.log.gz)

**Comment by gv74** [comment]
[openssl-3.0.0-alpha9-test.log.gz](https://github.com/openssl/openssl/files/5700971/openssl-3.0.0-alpha9-test.log.gz)

**Comment by gv74** [comment]
[openssl-3.0.0-alpha9-test-V=1.log.gz](https://github.com/openssl/openssl/files/5700973/openssl-3.0.0-alpha9-test-V.1.log.gz)

**Comment by gv74** [comment]
@makr Thank you for taking your time on this. But I'm not sure how building with xlC is relevant here. Anyway...

 I did a new configure/build/test again with the arguments you suggested. Nothing has changed. 
The new legacy provider library cannot be loaded on AIX. See attached log files.

I even tried like this:
````
$ LIBPATH=`pwd` apps/openssl aes-128-cbc -bufsize 113 -e -k test -provider-path providers -provider default -provider legacy -in ./p -out ./p.aes-128-cbc.cipher
aes-128-cbc: unable to load provider legacy
00000001:error::DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:
00000001:error::DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:
00000001:error::common libcrypto routines:provider_activate:init fail:crypto/provider_core.c:538:name=legacy
````
If I change legacy with fips, I get o different error (related to fips config?), but the library seems to be loaded:
````
LIBPATH=`pwd` apps/openssl aes-128-cbc -bufsize 113 -e -k test -provider-path providers -provider default -provider fips -in ./p -out ./p.aes-128-cbc.cipher 
aes-128-cbc: unable to load provider fips
00000001:error::Provider routines:SELF_TEST_post:missing config data:providers/fips/self_test.c:256:
00000001:error::Provider routines:ossl_set_error_state:fips module entering error state:providers/fips/self_test.c:350:
00000001:error::Provider routines:OSSL_provider_init:self test post failure:providers/fips/fipsprov.c:628:
00000001:error::common libcrypto routines:provider_activate:init fail:crypto/provider_core.c:538:name=fips
````
Something is wrong with legacy provider library on AIX.

BTW, even if I choose not to build the legacy provider (no-legacy), the legacy tests are still executed. Another bug.

The second batch of errors is, again, because of something related to legacy library:
````
$ LIBPATH=`pwd` test/evp_test -config test/default-and-legacy.cnf test/recipes/30-test_evp_data/evpciph_aes_ccm_cavs.txt
# ERROR:  @ test/evp_test.c:3603
# Failed to load config test/default-and-legacy.cnf
# 
# 
# Usage: evp_test [options] [file...]
# Valid options are:
#  -help           Display this summary
#  -list           Display the list of tests available
#  -test val       Run a single test by id or name
#  -iter int       Run a single iteration of a test
#  -indent +int    Number of tabs added to output
#  -seed int       Seed value to randomize tests with
#  -config infile  The configuration file to use for the libctx
# file  File to run tests on.
$ find . -name default-and-legacy.cnf
./test/default-and-legacy.cnf
````

**Comment by gv74** [comment]
````
$ truss apps/openssl aes-128-cbc -bufsize 113 -e -k test -provider-path `pwd`/providers -provider default -provider legacy -in ./p -out ./p.aes-128-cbc.cipher
````
[truss.log.gz](https://github.com/openssl/openssl/files/5701114/truss.log.gz)

**Comment by makr** [comment]
I am really sorry, @levitte and @gv74. Someone with a gcc tool chain needs to take this over. I do not see an obvious error. Comparing the logs provided here with the logs produced by the xlC tool chain, they appear to be similar, especially the linking steps. The xlC tool chain produces executables and libraries that do not fail:
```
...:/path/to/tmp/openssl-13336/openssl-3.0.0-alpha9$ LIBPATH=`pwd` apps/openssl aes-128-cbc -bufsize 113 -e -k test -provider-path providers -provider default -provider legacy -in ./p -out ./p.aes-128-cbc.cipher
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
...:/path/to/tmp/openssl-13336/openssl-3.0.0-alpha9$ LIBPATH=`pwd` apps/openssl version -a
OpenSSL 3.0.0-alpha9 26 Nov 2020 (Library: OpenSSL 3.0.0-alpha9 26 Nov 2020)
built on: Tue Dec 15 17:48:10 2020 UTC
platform: aix64-cc
options:  bn(64,64)
compiler: cc -qpic -q64 -qmaxmem=16384 -qro -qroconst -qthreaded -O -DB_ENDIAN -DOPENSSL_PIC -D_THREAD_SAFE -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/path/to/tmp/openssl-13336/ssl"
ENGINESDIR: "/path/to/tmp/openssl-13336/lib/engines-3"
MODULESDIR: "/path/to/tmp/openssl-13336/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: N/A
```
... and the test suite did not fail. So I think the handling of the gcc tool chain needs tweaking, but I have no means to do that.

**Comment by levitte** [comment]
@makr, thank you for taken the time, it's highly appreciated

**Comment by kaduk** [comment]
> BTW, even if I choose not to build the legacy provider (no-legacy), the legacy tests are still executed. Another bug.

(Note that this was fixed recently by #13595 though maybe #13705 is also needed as a final addendum.)

**Comment by gv74** [comment]
openssl 3.0.0-alpha10
- the problems reported above are still there
- fips self-tests does not w
[openssl-3.0.0-alpha10-test.log.gz](https://github.com/openssl/openssl/files/5786366/openssl-3.0.0-alpha10-test.log.gz)
[openssl-3.0.0-alpha10-V=1.log.gz](https://github.com/openssl/openssl/files/5786367/openssl-3.0.0-alpha10-V.1.log.gz)

ork.

**Comment by gv74** [comment]
Issue still present in openssl 3.0.0-alpha17.

**Comment by t8m** [comment]
@gv74 are the errors still the same as in the above test logs from alpha10? If not, could you please attach a new log from the tests with alpha17?

**Comment by t8m** [comment]
Also, could you please try to configure the build with -fno-strict-aliasing?

**Comment by gv74** [comment]
`make test` log attached: [openssl-3.0.0-alpha17-test.log.gz](https://github.com/openssl/openssl/files/6661031/openssl-3.0.0-alpha17-test.log.gz)

Also, `-fno-strict-aliasing` does not help at all.

**Comment by t8m** [comment]
The failures here are very different from the alpha10 ones.

I see at least two of them:
1. legacy provider cannot be loaded probably due to some bug in the DSO_ code
2. There is some problem with the test_cmp - unfortunately that one seems to be frequently broken on non-major platforms.

Could you look into the build tree providers directory if there is a legacy provider built?

**Comment by gv74** [comment]
Legacy provider cannot be loaded from alpha10 up to and including alpha17. Nothing has changed:

```
$ grep -c "unable to load provider legacy" *.log
openssl-3.0.0-alpha10-test.log:233
openssl-3.0.0-alpha11-test.log:233
openssl-3.0.0-alpha12-test.log:233
openssl-3.0.0-alpha13-test.log:233
openssl-3.0.0-alpha17-test.log:233
```
