### ISSUE TITLE
"openssl crl -CApath foo" fails where "openssl crl -CAfile foo/<hash>.<integer>" succeeds

### ISSUE THREAD

**Issue by vpelletier** [openssl/openssl#14066]
Version:
```
$ openssl version
OpenSSL 1.1.1i  8 Dec 2020
```
as of Debian sid package version 1.1.1i-3

Environment:
```
$ ls -l pem/
total 16
lrwxrwxrwx 1 vincent vincent   47  4 févr. 11:38 0a8e07a5.0 -> 82f1d99f3dde9fb92946e5d10ba2f8bb4a353347.ca.pem
lrwxrwxrwx 1 vincent vincent   47  4 févr. 11:38 0a8e07a5.1 -> 83f5182e9bad6150429df5a6a3f4772d76b79aba.ca.pem
lrwxrwxrwx 1 vincent vincent   48  4 févr. 11:38 0a8e07a5.r0 -> 82f1d99f3dde9fb92946e5d10ba2f8bb4a353347.crl.pem
lrwxrwxrwx 1 vincent vincent   48  4 févr. 11:38 0a8e07a5.r1 -> 83f5182e9bad6150429df5a6a3f4772d76b79aba.crl.pem
lrwxrwxrwx 1 vincent vincent   47  4 févr. 11:38 498bb543.0 -> 82f1d99f3dde9fb92946e5d10ba2f8bb4a353347.ca.pem
lrwxrwxrwx 1 vincent vincent   47  4 févr. 11:38 498bb543.1 -> 83f5182e9bad6150429df5a6a3f4772d76b79aba.ca.pem
lrwxrwxrwx 1 vincent vincent   48  4 févr. 11:38 498bb543.r0 -> 82f1d99f3dde9fb92946e5d10ba2f8bb4a353347.crl.pem
lrwxrwxrwx 1 vincent vincent   48  4 févr. 11:38 498bb543.r1 -> 83f5182e9bad6150429df5a6a3f4772d76b79aba.crl.pem
-rw-r--r-- 1 vincent vincent 1285  4 févr. 11:38 82f1d99f3dde9fb92946e5d10ba2f8bb4a353347.ca.pem
-rw-r--r-- 1 vincent vincent  666  4 févr. 11:38 82f1d99f3dde9fb92946e5d10ba2f8bb4a353347.crl.pem
-rw-r--r-- 1 vincent vincent 1285  4 févr. 11:38 83f5182e9bad6150429df5a6a3f4772d76b79aba.ca.pem
-rw-r--r-- 1 vincent vincent  666  4 févr. 11:38 83f5182e9bad6150429df5a6a3f4772d76b79aba.crl.pem
$ openssl crl -verify -no-CApath -no-CAfile -CAfile pem/0a8e07a5.0 -noout -in ./pem/83f5182e9bad6150429df5a6a3f4772d76b79aba.crl.pem
verify failure
$ openssl crl -verify -no-CApath -no-CAfile -CAfile pem/0a8e07a5.1 -noout -in ./pem/83f5182e9bad6150429df5a6a3f4772d76b79aba.crl.pem
verify OK
```

Notes:
- `*.*.pem` are named after the Authority Key Identifier contained in each file
- `*.ca.pem` contain a single CA (self-signed, `CA:TRUE`) certificate each, each generated from a different key pair
- `*.crl.pem` contain a single CRL each
- the subject of both CAs is the same. The use-case behind this is that one is replacing the other. Please do let me know if this is frowned upon.
- I do not know why there are two `c_rehash`-generated links for each file.

Up to here, everything is fine. Now, the bug:
```
$ openssl crl -verify -no-CApath -no-CAfile -CApath pem/ -noout -in ./pem/83f5182e9bad6150429df5a6a3f4772d76b79aba.crl.pem
verify failure
```

IOW: switching from `-CAfile` to `-CApath` and the command fails to locate the correct CA, and CRL validation fails.

Checking strace shows that both CAs are accessed, via the `0a8e07a5.*` symlinks:
```
$ strace openssl crl -verify -no-CApath -no-CAfile -CApath pem/ -noout -in ./pem/83f5182e9bad6150429df5a6a3f4772d76b79aba.crl.pem
[snip]
stat("pem/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "./pem/83f5182e9bad6150429df5a6a3f4772d76b79aba.crl.pem", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=666, ...}) = 0
read(3, "-----BEGIN X509 CRL-----\nMIIBxDC"..., 4096) = 666
close(3)                                = 0
stat("pem//0a8e07a5.0", {st_mode=S_IFREG|0644, st_size=1285, ...}) = 0
openat(AT_FDCWD, "pem//0a8e07a5.0", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1285, ...}) = 0
read(3, "-----BEGIN CERTIFICATE-----\nMIID"..., 4096) = 1285
read(3, "", 4096)                       = 0
close(3)                                = 0
stat("pem//0a8e07a5.1", {st_mode=S_IFREG|0644, st_size=1285, ...}) = 0
openat(AT_FDCWD, "pem//0a8e07a5.1", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1285, ...}) = 0
read(3, "-----BEGIN CERTIFICATE-----\nMIID"..., 4096) = 1285
read(3, "", 4096)                       = 0
close(3)                                = 0
stat("pem//0a8e07a5.2", 0x7ffe98f2d3c0) = -1 ENOENT (Aucun fichier ou dossier de ce type)
write(2, "verify failure\n", 15verify failure
)        = 15
exit_group(0)                           = ?
+++ exited with 0 +++
```

Having quickly read the code, I suspect this is related to the identical CA subjects (which means the CRLs have the same `issuer` despite having different `Authority Key Identifier` extension - which the code does not seem to be checking).

**Comment by vpelletier** [comment]
> ```
> - *.*.pem are named after the Authority Key Identifier contained in each file
> ```

Authority Key Identifier extension which contains only the keyid; no issuer and no serial.

**Comment by vpelletier** [comment]
For some perspective, stunnel4, which uses libssl, works with these CRLs when used to validate a certificate and given such `CApath`, so this issue is likely limited to the command-line `crl` tool.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by vpelletier** [comment]
@nhorman Is any input needed here ? None was requested, as far as I can see. Is this bug supposed to be fixed in a version I could test, and just pending confirmation ?

**Comment by nhorman** [comment]
Hello @vpelletier , regarding your question, possibly.  I marked this issue as inactive for 2 primary reasons:
1) The version that it was reported on is long out of support
2) It hasn't been commented on in 3 years.

In an effort to clean up our backlog, I'm marking issues as such inactive with the intent to close them, typically working under the assumption that either they are fixed, or that (as evidenced by the lack of attention), the core devevlopment team hasn't had bandwidth to give this item priority.

Since you responded, yes, I would ask that you retest this on the latest openssl release (currently 3.3.0), and report if its working or not.  If it is, great, we can close this.  If its not our option here is to mark this as a community issue, for which we would look to a community member outside of the development team to help solve. Note, that could be you, if you were so inclined, and we would greatly appreciate such an effort.  you've clearly done a great job diagnosing this problem, so it would be wonderful if we could count on you to pitch in with the improvement of openssl by posting a PR to fix it.

Let me know if you're interested, and I'll gladly assign this over to you.  Thank you!

**Comment by vpelletier** [comment]
First, a quick off-topic, fresh from building 3.3.1 from checkout and not having RTFM the build environment:
```
$ ./config --help
$ make -j12
```
is entertaining.

Back on topic:

```
$ ls -l
total 16
-rw-r--r-- 1 vincent vincent 1224 Jun 16 10:06 5416ac09aead2089ae6d60c1cc7b0d05453284ed.ca.pem
-rw-r--r-- 1 vincent vincent  638 Jun 16 10:06 5416ac09aead2089ae6d60c1cc7b0d05453284ed.crl.pem
-rw-r--r-- 1 vincent vincent 1224 Jun 16 10:06 cb334a82a5d3ae412c15ad3a6a72f8f91ef7323a.ca.pem
-rw-r--r-- 1 vincent vincent  638 Jun 16 10:06 cb334a82a5d3ae412c15ad3a6a72f8f91ef7323a.crl.pem
lrwxrwxrwx 1 vincent vincent   47 Jun 16 10:08 fb7ec3ce.0 -> 5416ac09aead2089ae6d60c1cc7b0d05453284ed.ca.pem
lrwxrwxrwx 1 vincent vincent   47 Jun 16 10:08 fb7ec3ce.1 -> cb334a82a5d3ae412c15ad3a6a72f8f91ef7323a.ca.pem
lrwxrwxrwx 1 vincent vincent   48 Jun 16 10:08 fb7ec3ce.r0 -> 5416ac09aead2089ae6d60c1cc7b0d05453284ed.crl.pem
lrwxrwxrwx 1 vincent vincent   48 Jun 16 10:08 fb7ec3ce.r1 -> cb334a82a5d3ae412c15ad3a6a72f8f91ef7323a.crl.pem
$ LD_LIBRARY_PATH=/home/vincent/git/openssl ~/git/openssl/apps/openssl version
OpenSSL 3.3.1 4 Jun 2024 (Library: OpenSSL 3.3.1 4 Jun 2024)
$ LD_LIBRARY_PATH=/home/vincent/git/openssl ~/git/openssl/apps/openssl crl -verify -no-CApath -no-CAfile -CAfile fb7ec3ce.0 -noout -in fb7ec3ce.r1
verify failure
809B01EFD57F0000:error:0200008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:crypto/rsa/rsa_pk1.c:79:
809B01EFD57F0000:error:02000072:rsa routines:rsa_ossl_public_decrypt:padding check failed:crypto/rsa/rsa_ossl.c:746:
809B01EFD57F0000:error:1C880004:Provider routines:rsa_verify:RSA lib:providers/implementations/signature/rsa_sig.c:785:
809B01EFD57F0000:error:06880006:asn1 encoding routines:ASN1_item_verify_ctx:EVP lib:crypto/asn1/a_verify.c:216:
$ LD_LIBRARY_PATH=/home/vincent/git/openssl ~/git/openssl/apps/openssl crl -verify -no-CApath -no-CAfile -CAfile fb7ec3ce.1 -noout -in fb7ec3ce.r1
verify OK
$ LD_LIBRARY_PATH=/home/vincent/git/openssl ~/git/openssl/apps/openssl crl -verify -no-CApath -no-CAfile -CApath ./ -noout -in fb7ec3ce.r1
verify failure
809B8751FC7E0000:error:0200008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:crypto/rsa/rsa_pk1.c:79:
809B8751FC7E0000:error:02000072:rsa routines:rsa_ossl_public_decrypt:padding check failed:crypto/rsa/rsa_ossl.c:746:
809B8751FC7E0000:error:1C880004:Provider routines:rsa_verify:RSA lib:providers/implementations/signature/rsa_sig.c:785:
809B8751FC7E0000:error:06880006:asn1 encoding routines:ASN1_item_verify_ctx:EVP lib:crypto/asn1/a_verify.c:216:
```

So the bug is still present in release 3.3.1 . I'm not sure why there is more output in case of validation failure, probably because I built with whatever the defaults are.

Strace output looks similar: both CAs are read, but verification still fails.
```
newfstatat(AT_FDCWD, "./", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "fb7ec3ce.r1", {st_mode=S_IFREG|0644, st_size=638, ...}, 0) = 0
openat(AT_FDCWD, "fb7ec3ce.r1", O_RDONLY) = 3
brk(0x5653076d1000)                     = 0x5653076d1000
lseek(3, 0, SEEK_CUR)                   = 0
lseek(3, 0, SEEK_CUR)                   = 0
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=638, ...}, AT_EMPTY_PATH) = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "-----BEGIN X509 CRL-----\nMIIBrTC"..., 4096) = 638
close(3)                                = 0
newfstatat(AT_FDCWD, ".//fb7ec3ce.0", {st_mode=S_IFREG|0644, st_size=1224, ...}, 0) = 0
openat(AT_FDCWD, ".//fb7ec3ce.0", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1224, ...}, AT_EMPTY_PATH) = 0
read(3, "-----BEGIN CERTIFICATE-----\nMIID"..., 4096) = 1224
futex(0x7f2155b4c994, FUTEX_WAKE_PRIVATE, 2147483647) = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
newfstatat(AT_FDCWD, ".//fb7ec3ce.1", {st_mode=S_IFREG|0644, st_size=1224, ...}, 0) = 0
openat(AT_FDCWD, ".//fb7ec3ce.1", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1224, ...}, AT_EMPTY_PATH) = 0
read(3, "-----BEGIN CERTIFICATE-----\nMIID"..., 4096) = 1224
read(3, "", 4096)                       = 0
close(3)                                = 0
newfstatat(AT_FDCWD, ".//fb7ec3ce.2", 0x7ffd3db951e0, 0) = -1 ENOENT (No such file or directory)
write(2, "verify failure\n", 15)        = 15
```

Bonus data point:
```
$ LD_LIBRARY_PATH=/home/vincent/git/openssl ~/git/openssl/apps/openssl crl -verify -no-CApath -no-CAfile -CApath ./ -noout -in fb7ec3ce.r0
verify OK
```

IOW, validating the first CRL (which matches the first CA) succeeds.

> Note, that could be you, if you were so inclined, and we would greatly appreciate such an effort. you've clearly done a great job diagnosing this problem, so it would be wonderful if we could count on you to pitch in with the improvement of openssl by posting a PR to fix it.

While my C is very rusty nowadays, I think this is at least a good challenge for me. I'll need some more time before I get around to it, as life is unfortunately busy at the moment. Hopefully things should get better in August.
