### ISSUE TITLE
What's the error "unsafe legacy renegotiation disabled" really mean?

### ISSUE THREAD

**Issue by ranierimazili** [openssl/openssl#21296]
Hello,

when executing the command below I've the following output:

**Command**
```
openssl s_client -connect somehost.com.br:443 -tls1_2
```
**Output**
```
CONNECTED(00000003)
804B1EBA547F0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../ssl/statem/extensions.c:879:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 3058 bytes and written 231 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1687864660
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

As you can see in the output, **Secure Renegotiation IS NOT supported**, but the error says something about **unsafe legacy renegotiation**. What it means?

A) That openssl cannot call this host because Secure Renegotiation IS NOT supported
B) That openssl cannot call this host because it's using the Legacy Renegotiation

Assuming the answer is B, if they disable Legacy Renegotiation will the first command work?

P.S¹: I'm using OpenSSL 3.0.2.
P.S²: I know that if I add the parameter -legacy_renegotation it will work, I just need to understand the failure reason behind the first command.

**Comment by mattcaswell** [comment]
TLSv1.2 (and earlier) support the concept of renegotiation. In 2009 (i.e. after the TLSv1.2 RFC was published), a flaw was discovered with how renegotiation works that could lead to an attack. After the attack was discovered a fix was deployed to all TLS libraries. In order for the fixed version of renegotiation to work both the client and the server need to support it.

The original (unfixed) version of renegotiation is known as "unsafe legacy renegotiation" in OpenSSL. The fixed version is known as "secure renegotiation". So either a peer does not have the fix, in which case it will be using "unsafe legacy renegotiation", or it does have the fix in which case it will be using "secure renegotation". 

So your (A) and (B) are actually the same thing.

If the server starts supporting secure renegotiation then the command will start to work.

**Comment by bandwiches** [comment]
How can I turn this off? TL;DR fresh install of python 3.12 is broken, cannot install any packages with Pip due to this error.  Cannot upgrade Pip due to this error.

**Comment by mattcaswell** [comment]
> How can I turn this off?

Try this (I've not tested this):

1) Create a config file that looks like this:

````
openssl_conf = default_conf

[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = ssl_default_sect

[ssl_default_sect]

Options = UnsafeLegacyRenegotiation
````
2) Run pip using that OpenSSL config file:

````
OPENSSL_CONF=/path/to/the/config/file/above.cnf pip ....whatever...
````

**Comment by davidben** [comment]
> How can I turn this off? TL;DR fresh install of python 3.12 is broken, cannot install any packages with Pip due to this error. Cannot upgrade Pip due to this error.

I would be pretty surprised if pip's servers do not support this 13-year-old extension. Can you post the error?

Are you connecting through some TLS-terminating proxy? Sometimes antivirus, firewall, or enterprise networking products will terminate TLS. In that case, it would be good to identify the vendor of the defective product and get them to implement the extension in the long run.

**Comment by bandwiches** [comment]
> > How can I turn this off? TL;DR fresh install of python 3.12 is broken, cannot install any packages with Pip due to this error. Cannot upgrade Pip due to this error.
> 
> I would be pretty surprised if pip's servers do not support this 13-year-old extension. Can you post the error?
> 
> Are you connecting through some TLS-terminating proxy? Sometimes antivirus, firewall, or enterprise networking products will terminate TLS. In that case, it would be good to identify the vendor of the defective product and get them to implement the extension in the long run.

Thanks for the quick response! **You are correct - SSL Inspection at the firewalls.**  SSL inspection or not, it seems there still exists a requirement to have some control over the terminating end in order to remediate the issue. At least as far as I can tell. I plan to investigate more this afternoon if time permits.

**Comment by davidben** [comment]
What is the SSL inspection product you are using? (Vendor and product version.) The config file flip may be usable as a temporary workaround, but the renegotiation bug is over 13 years old. It's well past time the vendor be informed and implement the fix.

**Comment by davidben** [comment]
Looks like you need to update to 10.2.5 or later:
https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-release-notes/pan-os-10-2-5-known-and-addressed-issues/pan-os-10-2-5-addressed-issues

> PAN-184630 | Fixed an issue where TLS clients, such as those using OpenSSL 3.0, enforced the TLS renegotiation extension (RFC 5746).

**Comment by bandwiches** [comment]
> Looks like you need to update to 10.2.5 or later: https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-release-notes/pan-os-10-2-5-known-and-addressed-issues/pan-os-10-2-5-addressed-issues
> 
> > PAN-184630 | Fixed an issue where TLS clients, such as those using OpenSSL 3.0, enforced the TLS renegotiation extension (RFC 5746).

I'll acknowledge this as an answer since it is technically correct, but the bigger issue still stands that users shouldn't be left in the dust waiting on server-side issues they have no control over.  Thanks!

**Comment by davidben** [comment]
https://github.com/openssl/openssl/issues/21296#issuecomment-1810043699 already answered what to do in the short term, no?

It is understandably frustrating when a deployment gets hit by changes to a default. At the same time, it takes changes like this to plug security risks. Here, clients cannot be sure they're protected against the renegotiation bug without enforcing the extension is present. As much as it's bad to break deployments that are (13 years!) behind, it's also bad to leave the vast majority of correct deployments unprotected.

If there were a mechanism to phone up every TLS deployment and remind them to apply some 13-year-old fix before making the change, that would be amazing. Sadly, there isn't. Absent that, the best one can do is wait until the balance has shifted and flip the default.

That will invariably break the stragglers, like Palo Alto Networks here, that didn't get the memo. (Evidently PAN, despite shipping a TLS product, have not paying attention to industry-wide developments in TLS for the past 13 years...) So you provide a short-term mechanism to turn it back off. But since the goal is, ultimately, to get everyone into the safe configuration, the response to such an incident is always two fold:

1. Here is the knob to you can toggle to fix it in the short term (@mattcaswell's response)
2. Here is what your server should be doing to avoid needing the knob in the long term (my response)

Both tracks are important. Yes, it's expected the long-term fix will take time. That's why the short-term fix is available. But all the more reason to get the ball rolling on the long-term fix too. I asked for the vendor information above to do just that:

* If it happened that PAN hadn't provided a fix yet, I would have reached out to them to get them to fix it
* It turned out they had provided a fix, so hopefully now that you know it's 10.2.5, that will make the long-term fix easier for your deployment

(I should note that I'm not speaking on behalf of OpenSSL here. But I often manage such decisions in Chrome, so I thought I'd elaborate a bit on how these go, and why I tried to identify buggy product. Indeed I hope we can require this extension in Chrome  in the future. Though, with the current numbers, I think I need to do some more outreach before it's viable on the web, regrettably.)

**Comment by t8m** [comment]
Great write up @davidben !

It looks like TLS-1.2 will be obsolete earlier than all the deployments of servers (or firewalls) which do not support this extension will be updated.

**Comment by bandwiches** [comment]
@davidben  totally agree with your response, it is definitely two-fold.  I actually don't have an issue forcing users to the new method, my concern is this workaround being labeled "not recommended" and yet it is the only workaround seen over and over again across the web. I appreciate your write-up and I think it will definitely help others in my position.

@t8m  you are spot-on.  Just look at [Microsoft: Windows](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/tls-1-0-and-tls-1-1-soon-to-be-disabled-in-windows/ba-p/3887947) and how they are just now disabling TLS 1.0 / 1.1 in Windows as of August 2023.  Another example of [Microsoft: Azure Front Door](https://learn.microsoft.com/en-us/azure/frontdoor/front-door-faq#what-tls-versions-are-supported-with-azure-front-door-) that doesn't even support TLS 1.3 as of today.

**Comment by davidben** [comment]
Considering that almost all TLS 1.2 implementations implement the extension, and TLS 1.3 doesn't need the extension, it is not actually possible for that to be true. The number of servers that need unsafe renegotiation is much, much lower than the number of servers that need TLS 1.2.

**Comment by t8m** [comment]
What I wrote above was not meant to be fully serious. And by TLS-1.2 being obsolete I meant _it will be marked as obsolete by IETF RFC the same way as 1.1 and 1.0 is_. I did not mean by that it won't be used on public internet at all.

**Comment by obayit** [comment]
I get this error when I try to download a file from python code, or with wget. how can I fix this for python?

**Comment by obayit** [comment]
For python fix, see this [answer on stackoverflow](https://stackoverflow.com/a/73519818/3557761).

**Comment by bandwiches** [comment]
If anyone is running into this issue on `Windows`, the only way I could get anything to pick up the `OPENSSL_CONF` environment variable was by installing `Powershell 7.x`.  Prior to installing Powershell 7, setting the environment variable had no effect. After installing Powershell 7, I had success in both shells.

This is a fresh image where the only installs were:
* Python 3.12 (via installer)
* Powershell 7 (via winget)
* Git for Windows (via winget)

Note: openssl is not installed, it's bundled with Python 3.12

I set the environment variable via `$env:OPENSSL_CONF="path/to/openssl.cnf"`

Hope this helps!

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
