### ISSUE TITLE
TLS with Brainpool Curves

### ISSUE THREAD

**Issue by vbrandl** [openssl/openssl#21346]
I want do use OpenSSL with a key on the brainpoolP256r1 curve.
I generated the certificate like this:

```shell
openssl ecparam -name brainpoolP256r1 -genkey -out key.pem
openssl req -new -x509 -sha256 -days 365 -key key.pem -out cert.pem
```

I start the server like this:

```
openssl s_server -cert cert.pem -key key.pem -www
```

And try to connect using

```
openssl s_client -connect 127.0.0.1:4433
```

On the server side, I get the following error:

```
4077B4A2DF7F0000:error:0A0000C1:SSL routines:tls_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:2220:
```

And on the client side:

```
40273B96297F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1605:SSL alert number 40
```

To have a shared cipher, I also tried

```
openssl s_server -cert cert.pem -key key.pem -www -cipher ECDHE-ECDSA-AES128-GCM-SHA256
openssl s_client -connect 127.0.0.1:4433 -cipher ECDHE-ECDSA-AES128-GCM-SHA256
```

And got the same errors as above.

I tried using the following OpenSSL versions:

* `OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)`
* `OpenSSL 1.1.1t  7 Feb 2023`

**Comment by t8m** [comment]
This has been resolved on master branch already. However I can reproduce it on 3.0 branch. @mattcaswell any idea?

**Comment by mattcaswell** [comment]
OpenSSL 3.0/3.1 does not support the brainpool curves with TLSv1.3 - which is what will be negotiated with the default s_server/s_client commands provided above. The master branch (what will become 3.2) does have this support (added via #7485 and later commits).

**Comment by HLFH** [comment]
@mattcaswell Getting this issue with `openssl 3.1.1`. Can we not have the fix in `openssl` 3.1.2? Or could you not release `openssl` 3.2 in `beta1` then? ;)

**Comment by mattcaswell** [comment]
We don't backport features into stable releases. 3.2 should be going into alpha in the not too distant future.

**Comment by vbrandl** [comment]
> OpenSSL 3.0/3.1 does not support the brainpool curves with TLSv1.3

I'm still struggling with this problem. I tried explicitly using TLSv1.2:

```
openssl s_server -cert cert.pem -key key.pem -www -curves brainpoolP256r1 -tls1_2 -port 8443
openssl s_client -showcerts -connect localhost:8443 -tls1_2
```

But I still get the SSL alert number 40 error:

```
406775933E7F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1586:SSL alert number 40
```

**Comment by vbrandl** [comment]
This is still a problem. I'm now testing with OpenSSL 3.2.0:

```
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)
```

TLS 1.3 works:

```
openssl s_server -cert cert.pem -key key.pem -www -tls1_3
```

```
$ openssl s_client -connect 127.0.0.1:4433 -tls1_3 
Connecting to 127.0.0.1
CONNECTED(00000003)
...
```

But TLS 1.2 with brainpool still fails:

```
openssl s_server -cert cert.pem -key key.pem -www -tls1_2
```

```
$ openssl s_client -connect 127.0.0.1:4433 -tls1_2
Connecting to 127.0.0.1
CONNECTED(00000003)
4067E314D07F0000:error:0A000410:SSL routines:ssl3_read_bytes:ssl/tls alert handshake failure:ssl/record/rec_layer_s3.c:861:SSL alert number 40
```

**Comment by vbrandl** [comment]
I got it working now. I had to explicity set the curves to use on both the client and the server

```
$ openssl s_server -cert cert.pem -key key.pem -tls1_2 -curves brainpoolP256r1 -accept 12345
```

```
$ openssl s_client -connect localhost:12345 -tls1_2 -curves brainpoolP256r1
Connecting to ::1
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 C=AU, ST=Some-State, O=Internet Widgits Pty Ltd
```

**Comment by dlenskiSB** [comment]
There are, as far as I can tell, _only 2 servers on the entire Internet_ using the `brainpoolP256r1` curve in their EC certs. They cannot be opened using any standard client (["security through obscurity"(https://en.wikipedia.org/wiki/Security_through_obscurity), I guess?)

Both of them appear to be in Germany according to their IP addresses and cert details.

Are you *sure* that you really want to stand out like a sore thumb in this way? 🤨

* https://www.shodan.io/host/98.64.197.140#443
* https://www.shodan.io/host/185.188.0.72#8443

**Comment by vbrandl** [comment]
That's simply wrong. I know of many more servers, that use brainpool keys. A new policy for the German energy market requires everybody to use brainpool keys to encrypt market communication since April 2024. The smart metering infrastructure is also required to use brainpool. So at least every participant in the German energy market runs a server using brainpool for each of its market roles.

This has nothing to do with security through obscurity. It's simply about following state mandated regulations (a discussion can be had about weather that regulation makes sense but for now it is regulated as it is and has to be followed).

Evidently Shodan is not reliable in finding these servers but that doesn't change the reality of brainpool being used.

I'm not sure what you are trying to insinuate with your comment. It's not helpful to my problem...

If you are actually interested, here are some documents (in German):

* [AS4 Profile](https://www.bundesnetzagentur.de/DE/Beschlusskammern/1_GZ/BK6-GZ/2021/BK6-21-282/Mitteilung02/AS4%20Profil.pdf?__blob=publicationFile&v=1): The second paragraph in `2.2.6.2.1 Signature` states: `The used curve MUST be BrainpoolP256r1`
* [Cryptographic specifications for projects of the
Federal Government](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03116/BSI-TR-03116-3.pdf?__blob=publicationFile&v=9): 
  + `2.2 Domain parameters for elliptic curves` lists 3 brainpool curves (aside 2 secp curves)
  + `3 Public Key Infrastructure` requires CAs to use brainpool when issuing certificates
  + `4.1.1 Authentication and TLS certificates` required brainpool for mTLS
  + and a few more mentions, if you search the document for `brainpool`

**Comment by dlenskiSB** [comment]
> A new policy for the German energy market requires everybody to use brainpool keys to encrypt market communication since April 2024. 

Very very interesting.

Though still rather confusing, because (as far as _I_ can tell) there is no widely-used TLS client library that supports these curves out-of-the-box without additional configuration.

> This has nothing to do with security through obscurity or "standing out like a sore thumb". It's simply about following state mandated regulations (a discussion can be had about weather that regulation makes sense but for now it is regulated as it is and has to be followed). So yes, I am sure that's what I want!

Thank you for cluing me in on this.

(And you're right, my previous message jumped to some incorrect and dumb conclusions. I've deleted it. 🙏 )

**Comment by vbrandl** [comment]
Aside OpenSSL, here is one library, I know of, that supports brainpool: [Bouncy Castle](https://www.bouncycastle.org/). But you are right, it's not out of the box and we actually couldn't run it under Java 17 (or up) and had to go back to Java 11...

OpenSSL can work with brainpool keys and therefore any webserver that is linked against a recent enough version of OpenSSL, does too.
I know it works with nginx with some caveats: you can't use brainpool and non-brainpool certificates on the same port, so we had to get another public IP address for brainpool stuff and forward requests from that IP to the brainpool TLS port on our nginx.

I've been working on implementing this stuff for over a year and every implementation, I know of, uses Bouncy Castle (and by extension there are only implementation in Java or C#). If not Bouncy Castle, they use a HSM and communicate using PKCS 11.
[Edit: There actually is [this implementation](https://github.com/schleupen/as4-connect-business-api-adapter/) which uses C# and doesn't reference Bouncy Castle in the repository, so the C# cryptography stack might actually natively support brainpool but I haven't looked deeper]

I agree with your general sentiment: This sucks. And I really, really know that and I kinda know what I'm doing. I fought for many months to get this up and running. But here we are... running services, that use brainpool, to justify some regulatory body's existence [that's too harsh, but I'm traumatized by this topic] (Brainpool was proposed and standardized by the German BSI [federal office for information security])

**Comment by M-Inamullah** [comment]
Hi @t8m, @mattcaswell @vbrandl, I am facing the same issue on the 3.1.2 version, I also tried to update it to the latest version (3.4.0), but the same error appeared until I specifically mentioned the **-curves** in the command on the server and client side as well as mentioned above by @vbrandl 

This issue only occurs in the Brainpool curves, I also tested on other curves it works fine (no need to specify the curves)

Is there a way to configure the openssl to use specifically brainpool curves or does it normally happen with brainpool curves to specify what is the reason for this behaviour under this scenario? 
I really appreciate any help you can provide.
Thanks
