### ISSUE TITLE
Crashed when used openssl which enabled "Control Flow Guard" on Windows x64

### ISSUE THREAD

**Issue by nickychen123456** [openssl/openssl#22944]
Here is the steps I build the openssl 3.1.1:

1. run command **perl Configure VC-WIN64A-masm no-ssl3 no-autoload-config CFLAGS="/W3 /wd4090 /nologo /O2 /guard:cf"** to config
3. run command "nmake" to build

When I used the openssl lib, I got the crash:

![image](https://github.com/openssl/openssl/assets/98001929/48ad6b65-4717-4cae-836a-6a9190d5cb88)
![image](https://github.com/openssl/openssl/assets/98001929/e5d25723-07c7-4565-98a3-69918689c198)

Can we enable the "CFG" on win x64 with the config VC-WIN64A-masm? Am I use the correct way to enable CFG? I used the same steps to build openssl 1.1.1, it works fine, no crash occurred.

**Comment by nickychen123456** [comment]
BTW，when I run test, I got the below failure:

05-test_pbe.t ......................
    # ERROR: (bool) 'PKCS5_PBE_keyivgen(ctx, pbe_password, strlen(pbe_password), algor->parameter, cipher, md, 1) == true' failed @ test\pbetest.c:77
    # false
    # 18830300:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto\evp\evp_fetch.c:341:Global default library context, Algorithm (PBKDF1 : 0), Properties (<null>)
    # OPENSSL_TEST_RAND_ORDER=1701652449
    not ok 1 - test_pkcs5_pbe_rc4_md5
# ------------------------------------------------------------------------------
    # ERROR: (bool) 'PKCS5_PBE_keyivgen(ctx, pbe_password, strlen(pbe_password), algor->parameter, cipher, md, 1) == true' failed @ test\pbetest.c:77
    # false
    # 18830300:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto\evp\evp_fetch.c:341:Global default library context, Algorithm (PBKDF1 : 0), Properties (<null>)
    # OPENSSL_TEST_RAND_ORDER=1701652449
    not ok 2 - test_pkcs5_pbe_des_sha1

What could be the cause of these errors? Is it a mistake in my build steps or an issue with my environment? Will this error result in a crash?

**Comment by slontis** [comment]
PBKDF1 comes from the legacy provider.. Does your pbetest.c file contain the following?

````
int setup_tests(void)
{
#ifdef OPENSSL_NO_AUTOLOAD_CONFIG
    /* Load required providers if not done via configuration */
    legacy = OSSL_PROVIDER_load(NULL, "legacy");
    dflt = OSSL_PROVIDER_load(NULL, "default");
    if (!TEST_ptr(legacy) || !TEST_ptr(dflt)) {
        cleanup_tests();
        return -1;
    }
#endif
````
i.e. It does something special when you use  no-autoload-config

**Comment by nickychen123456** [comment]
@slontis No, here is my pbetest.c

int setup_tests(void)
{
#if !defined OPENSSL_NO_RC4 && !defined OPENSSL_NO_MD5
    ADD_TEST(test_pkcs5_pbe_rc4_md5);
#endif
#if !defined OPENSSL_NO_DES && !defined OPENSSL_NO_SHA1
    ADD_TEST(test_pkcs5_pbe_des_sha1);
#endif

    return 1;
}

Is there something wrong?

**Comment by slontis** [comment]
Probably worth getting the latest..
either 3.1.4 or 3.2 (See www.openssl.org/source)
See  github.com/openssl/openssl/pull/21621
(This fixes your test issue, but maybe not your other issue)

**Comment by nickychen123456** [comment]
@slontis  Thank you so much, So can we enable CFG on windows x64 platform, We suspect that the crash is caused by enabling Control Flow Guard (CFG), but we are currently uncertain about how to fix this issue. Can you provide any assistance or suggestions?

**Comment by nickychen123456** [comment]
@slontis @nhorman , From the callstack, we know that the crash occured in function:

`int ossl_cipher_hw_generic_cbc(PROV_CIPHER_CTX *dat, unsigned char *out,
                               const unsigned char *in, size_t len)
{
    if (dat->stream.cbc)
        (*dat->stream.cbc) (in, out, len, dat->ks, dat->iv, dat->enc);
    else if (dat->enc)
        CRYPTO_cbc128_encrypt(in, out, len, dat->ks, dat->iv, dat->block);
    else
        CRYPTO_cbc128_decrypt(in, out, len, dat->ks, dat->iv, dat->block);

    return 1;
}`

If this is a CFG issue, then it is probably caused by "(*dat->stream.cbc) (in, out, len, dat->ks, dat->iv, dat->enc);", and through our tests, we found that the CFG verification failed for the following three functions.

![image](https://github.com/openssl/openssl/assets/98001929/069ef94e-00f2-427b-b6b4-473abd96cd6b)

So we believe that the (*dat->stream.cbc)  should be pointed to cbc_decrypt_bulk, is that right? Can you provide us with some direction or suggestions for resolving this issue? Thanks a lot.

**Comment by slontis** [comment]
The issue is related to https://github.com/openssl/openssl/issues/22896.
It may be some time before this is addressed.

**Comment by nickychen123456** [comment]
Hi @slontis We have some new findings regarding this issue, On the devices that has no issue, I found that after ossl_cipher_generic_block_update, it does not proceed to the ossl_cipher_hw_generic_cbc function but instead goes to cipher_hw_aesni_ecb. This indicates that on the devices without issues and those with issues, the difference lies in the assignment of ctx->hw->cipher.

So can you help to tell me how ctx->hw->cipher is specifically assigned? Why is ctx->hw->cipher assigned to ossl_cipher_hw_generic_cbc instead of cipher_hw_aesni_ecb on the machines with issues?

**Comment by nhorman** [comment]
This seems like another undefined behavior detection.

the cbc128_f function pointer is defined as:
```
typedef void (*cbc128_f) (const unsigned char *in, unsigned char *out,          
                          size_t len, const void *key,                          
                          unsigned char ivec[16], int enc);
```

And while I haven't looked it up yet, I imagine the function signature of the function this pointer points to doesn't match.  Its part of the class of errors tracked here:
https://github.com/openssl/openssl/issues/22896

**Comment by nickychen123456** [comment]
Hi @nhorman How should we fix this issue or continue researching it? I would greatly appreciate any guidance or suggestions you could provide. Our app is unable to launch due to this issue.

**Comment by nhorman** [comment]
The thing to do is format the callback funciton that cbc128_f points to to have the same arguments are return type as the definition above..  You can see examples of this in the LHASH code thunk routines

**Comment by nickychen123456** [comment]
Hi @nhorman @asiplas Here's the information about my crashing machine:

![image](https://github.com/user-attachments/assets/bbab9fcc-5695-4a10-8c3c-d1d6be4c9463)

The crash occurs at the location shown in the image:

![image](https://github.com/user-attachments/assets/3327e22f-f97b-47ab-99a0-948334347d79)
![image](https://github.com/user-attachments/assets/29fb2f03-dfa2-4948-93b3-cbb84cc43819)


We can see that dat->stream.cbc is set to the function AES_cbc_encrypt, and then the CFG check fails. I have tested this machine and confirmed that it does not support the AES-NI instruction set. Shouldn't this cbc be set to something other than AES_cbc_encrypt? Do you have any suggestions to fix this issue? If you could provide a patch, it would be greatly appreciated.

**Comment by nhorman** [comment]
I made a suggestion above.  The function that stream.cbc points to needs to have the same prototype as the cbc_128f type

**Comment by nickychen123456** [comment]
@nhorman I see that AES_cbc_encrypt is defined in aes_cbc.c, but it seems that during the OpenSSL build, aes_cbc.c is not compiled, and it looks like the implementation from aes-x86_64.asm is used directly. Are you suggesting that I should modify the implementation in the aes-x86_64.asm file?

**Comment by nhorman** [comment]
The asm code isn't typed (as its asm), its the header file (and then all the corresponding implementations that need to be changed.

**Comment by nickychen123456** [comment]
Hi @nhorman 

Just wanted to update you that after adding the no-asm flag when building OpenSSL to disable the use of assembly code, the problem was resolved. So, it was indeed an issue with the assembly code that caused the CFG check to fail, right?

**Comment by nhorman** [comment]
I'm honestly kind of suprised that worked for you.  The prototype for the stream.cbc function is where this is occuring (and we have lots of instances of this from the referenced issues).  building with no-asm should just switch your environment to using a non-asm code path, which should still have the prototyping errors

**Comment by nickychen123456** [comment]
@nhorman However, adding no-asm does solve my problem, but we're concerned about the performance impact and hesitant to use this solution. Also, I noticed that the aes_cbc.c file was not compiled when building version 3.1.5. Is this correct?

**Comment by nickychen123456** [comment]
Hi @nhorman 
We now want to follow the above plan and would like your guidance on the following two questions:

How can we include aes_cbc.c when compiling OpenSSL 3.1.5?
How can we prevent the AES_cbc_encrypt function definition from being generated in the aes-x86_64.asm file? Do we need to modify the aes-x86_64.pl file?
We would greatly appreciate it if you could provide detailed instructions on how to do this.

**Comment by nhorman** [comment]
1) aes_cbc is always included in openssl-builds by default
2) you can disable asm by configuring with no-asm, as you've done above.

**Comment by nickychen123456** [comment]
Hi @nhorman 
I am absolutely certain that aes_cbc.c is not compiled by default in version 3.1.5, I just want to know how to add it to the build process.
I don't want to add no-asm because I don not want to disable all assembly code.

**Comment by nickychen123456** [comment]
Hi @nhorman, Is the following change acceptable? I tested it and found that it can be added to the Makefile. Making this change shouldn't cause any other issues, right?

diff --git a/crypto/aes/build.info b/crypto/aes/build.info
index aff318b3..25295bf6 100644
--- a/crypto/aes/build.info
+++ b/crypto/aes/build.info
@@ -67,7 +67,7 @@ IF[{- !$disabled{asm} -}]
 ENDIF
 
 $COMMON=aes_misc.c aes_ecb.c $AESASM
-SOURCE[../../libcrypto]=$COMMON aes_cfb.c aes_ofb.c aes_wrap.c
+SOURCE[../../libcrypto]=$COMMON aes_cbc.c aes_cfb.c aes_ofb.c aes_wrap.c
 IF[{- !$disabled{'deprecated-3.0'} -}]
   SOURCE[../../libcrypto]=aes_ige.c
 ENDIF

**Comment by paulidale** [comment]
IMO, no.  You will have built AES in CBC mode.  It is **always** built.  It's not always the aes_cbc.c file that is used when assembly implementations are available.  Try running `./util/wrap.pl apps/openssl list -cipher-algorithms` in your build directory.  AES-128-CBC should be listed as are other flavours of AES in CBC mode.

If you are unwilling to turn off assembly code, you will either have to submit a pull request adding control flow guard support to the assembly code or build without control flow guard.  There simply is no other option.

**Comment by nickychen123456** [comment]
Hi @paulidale , So the assembly code for AES cbc encryption in OpenSSL doesn't support CFG, right? 

Additionally, the issue we're encountering occurs on AMD machines. When we enable CFG, the OpenSSL crashes, and the reason is that the AES_cbc_encrypt function causes the CFG check to fail, as I mentioned earlier. So, I don't want to use the assembly implementation of AES_cbc_encrypt and would prefer to use the one in aes_cbc.c. Besides modifying crypto/aes/build.info, I also made the following changes:

`diff --git a/crypto/aes/asm/aes-x86_64.pl b/crypto/aes/asm/aes-x86_64.pl
index 25f7ded9..b8b6beee 100644
--- a/crypto/aes/asm/aes-x86_64.pl
+++ b/crypto/aes/asm/aes-x86_64.pl
@@ -1732,14 +1732,14 @@ my $aes_key="80(%rsp)";		# copy of aes_key
 my $mark="80+240(%rsp)";	# copy of aes_key->rounds
 
 $code.=<<___;
-.globl	AES_cbc_encrypt
-.type	AES_cbc_encrypt,\@function,6
+.globl	AES_cbc_encrypt1
+.type	AES_cbc_encrypt1,\@function,6
 .align	16
 .extern	OPENSSL_ia32cap_P
 .globl	asm_AES_cbc_encrypt
 .hidden	asm_AES_cbc_encrypt
 asm_AES_cbc_encrypt:
-AES_cbc_encrypt:
+AES_cbc_encrypt1:
 .cfi_startproc
 	endbranch
 	cmp	\$0,%rdx	# check length
@@ -2892,8 +2892,8 @@ cbc_se_handler:
 	.rva	.LSEH_end_AES_set_decrypt_key
 	.rva	.LSEH_info_AES_set_decrypt_key
 
-	.rva	.LSEH_begin_AES_cbc_encrypt
-	.rva	.LSEH_end_AES_cbc_encrypt
+	.rva	.LSEH_begin_AES_cbc_encrypt1
+	.rva	.LSEH_end_AES_cbc_encrypt1
 	.rva	.LSEH_info_AES_cbc_encrypt
 
 .section	.xdata
`

These changes solve my issue where the app fails to launch on my AMD machine. Our app must have CFG enabled, and we cannot use no-asm to disable all assembly code. Therefore, I just want to know if these changes can be considered as a workaround? We genuinely don't know how to resolve the issue we're encountering while keeping CFG enabled and not disabling assembly code.

**Comment by paulidale** [comment]
They would be a work around.  They would not be accepted into the projects code base I suspect.

**Comment by nickychen123456** [comment]
Hi @paulidale Thanks, we would task it as a work around as we do not have other soultions

**Comment by paulidale** [comment]
The proper solution is to modify the assembly functions to support CFG.  This will probably require community input I suspect.

**Comment by nickychen123456** [comment]
hi @nhorman 

When I renamed the AES_cbc_encrypt in aes-x86_64.pl add aes_cbc.c into build like I mentioned above, then change the code like this:

![image](https://github.com/user-attachments/assets/0d4b8ec4-c078-4e29-ba59-977e3c18ae35)

It also works
