### ISSUE TITLE
[rt.openssl.org #4276] Possible bug - ts -verify -digest, error:ts_rsp_verify.c:291:

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2473]
Migrated from [rt.openssl.org#4276](https://rt.openssl.org/Ticket/Display.html?id=4276) (status was 'open')

Requestors:
* mario.scalabrino@andifyou.com

Attachments:
* [01-ISOTIPO_GRADIENT-150x150.png](https://rt.openssl.org/Ticket/Attachment/60113/36822/01-ISOTIPO_GRADIENT-150x150.png)
* [linea.jpg](https://rt.openssl.org/Ticket/Attachment/60113/36823/linea.jpg)
* [icon_phone.jpg](https://rt.openssl.org/Ticket/Attachment/60113/36824/icon_phone.jpg)
* [icon_mail.jpg](https://rt.openssl.org/Ticket/Attachment/60113/36825/icon_mail.jpg)
* [icon_web.jpg](https://rt.openssl.org/Ticket/Attachment/60113/36826/icon_web.jpg)
* [linkedin_icon.jpg](https://rt.openssl.org/Ticket/Attachment/60113/36827/linkedin_icon.jpg)
* [facebook_icon.jpg](https://rt.openssl.org/Ticket/Attachment/60113/36828/facebook_icon.jpg)
* [twitter_icon.jpg](https://rt.openssl.org/Ticket/Attachment/60113/36829/twitter_icon.jpg)
* [ScenarioOpensslNamirial.zip](https://rt.openssl.org/Ticket/Attachment/60113/36830/ScenarioOpensslNamirial.zip)
* [03-IMAGOTIPO_GRADIENT-150x150.png](https://rt.openssl.org/Ticket/Attachment/62773/38745/03-IMAGOTIPO_GRADIENT-150x150.png)
* [linea.jpg](https://rt.openssl.org/Ticket/Attachment/62773/38746/linea.jpg)
* [icon_phone.jpg](https://rt.openssl.org/Ticket/Attachment/62773/38747/icon_phone.jpg)
* [icon_mail.jpg](https://rt.openssl.org/Ticket/Attachment/62773/38748/icon_mail.jpg)
* [icon_web.jpg](https://rt.openssl.org/Ticket/Attachment/62773/38749/icon_web.jpg)
* [linkedin_icon.jpg](https://rt.openssl.org/Ticket/Attachment/62773/38750/linkedin_icon.jpg)
* [facebook_icon.jpg](https://rt.openssl.org/Ticket/Attachment/62773/38751/facebook_icon.jpg)
* [twitter_icon.jpg](https://rt.openssl.org/Ticket/Attachment/62773/38752/twitter_icon.jpg)

From mario.scalabrino@andifyou.com on 2016-01-28 16:16:28:
```
Good afternoon Openssl,

please forward this email to whomever it may concern.

I receive an error and the Timestamping provider suspects it is a 
Openssl bug.
Could you please check if it is openssl or the certificate?


This is when the error occurr
/openssl ts -verify -digest 
e16db7d30581e44a5540f19553852b5a4e4e26f9adc365cc846f94038ee33025 -in 
/tmp/namirial.tsr -CAfile /tmp/NamirialCATSA.pem
(result:)
*************
*Verification: FAILED**
**140236013643424:error:2F067065:time stamp 
routines:TS_CHECK_SIGNING_CERTS:ess signing certificate 
error:ts_rsp_verify.c:291:*/


I attach a complete reproduction scenario. I don't know if it is a 
problem of this TSA certificate or in Openssl due to sha256 digest, 
please help.


(in the curl command I cannot provide you the username and password, it 
is a paid service)

Attached are the files resulting from the below commands in sequence and 
the certificate of the TSA, but I'm sure you can check yourself the last 
command where the error occur and  advice.

you can copy and paste the commands below if you're in Linux Ubuntu and 
the files are in the /tmp/ folder

*Reproduction scenario:*

OS: Ubuntu 14.04
Openssl version: OpenSSL 1.0.1f 6 Jan 2014



Generate tsq:
openssl ts -query -digest 
e16db7d30581e44a5540f19553852b5a4e4e26f9adc365cc846f94038ee33025 -sha256 
-cert -out /tmp/namirial.tsq

Readable tsq:
openssl ts -query -in /tmp/namirial.tsq  -text
(result:)
************
Hash Algorithm: sha256
Message data:
     0000 - e1 6d b7 d3 05 81 e4 4a-55 40 f1 95 53 85 2b 5a .m.....JU@..S.+Z
     0010 - 4e 4e 26 f9 ad c3 65 cc-84 6f 94 03 8e e3 30 25 NN&...e..o....0%
Policy OID: unspecified
Nonce: 0x8CA62B5766A29A8B
Certificate required: yes
Extensions:
****************


Generate tsr (using curl)
curl -u xxxxxxx:yyyyyy -s --data-binary @/tmp/namirial.tsq -H 
'Content-Type: application/timestamp-query' -H 'Pragma: no-cache' -H 
'Accept: application/timestamp-reply' --output /tmp/namirial.tsr 
http://timestamp.firmacerta.it

Readable tsr
openssl ts -reply -in /tmp/namirial.tsr  -out /tmp/readable_tsr.txt -text

(result:)
******************
Status info:
Status: Granted.
Status description: Operation Okay
Failure info: unspecified

TST info:
Version: 1
Policy OID: 1.3.6.1.4.1.36203.2.1
Hash Algorithm: sha256
Message data:
     0000 - e1 6d b7 d3 05 81 e4 4a-55 40 f1 95 53 85 2b 5a .m.....JU@..S.+Z
     0010 - 4e 4e 26 f9 ad c3 65 cc-84 6f 94 03 8e e3 30 25 NN&...e..o....0%
Serial number: 0x1947FD96B97A42DE
Time stamp: Jan 28 14:56:16 2016 GMT
Accuracy: unspecified seconds, 0x01F4 millis, unspecified micros
Ordering: no
Nonce: 0x8CA62B5766A29A8B
TSA: unspecified
Extensions:
************************


Verify
openssl ts -verify -digest 
e16db7d30581e44a5540f19553852b5a4e4e26f9adc365cc846f94038ee33025 -in 
/tmp/namirial.tsr -CAfile /tmp/NamirialCATSA.pem
(result:)
*************
*Verification: FAILED**
**140236013643424:error:2F067065:time stamp 
routines:TS_CHECK_SIGNING_CERTS:ess signing certificate 
error:ts_rsp_verify.c:291:*
***************



-- 
Untitled Document
*Certify Doc <http://www.certifydoc.eu>* 	

*MARIO SCALABRINO *

Founder & CEO

(+34) 680 128 282

mario.scalabrino@andifyou.com <mailto:mario.scalabrino@andifyou.com>

www.certifydoc.eu <http://www.certifydoc.eu>

Linkedin <https://www.linkedin.com/in/andifyou>Facebook 
<https://www.facebook.com/certifydoc>Twitter 
<https://twitter.com/certifydoc>


```

From mario.scalabrino@andifyou.com on 2016-02-17 13:49:21:
```
Hello Openssl,

is there any update? Do you need more information?

Thank you

Cheers

Mario Scalabrino

Untitled Document
*Certify Doc <http://www.certifydoc.eu>* 	

*MARIO SCALABRINO *

Founder & CEO

(+34) 680 128 282

mario.scalabrino@andifyou.com <mailto:mario.scalabrino@andifyou.com>

www.certifydoc.eu <http://www.certifydoc.eu>

Linkedin <https://www.linkedin.com/in/andifyou>Facebook 
<https://www.facebook.com/certifydoc>Twitter 
<https://twitter.com/certifydoc>


On 28/01/2016 17:16, The default queue via RT wrote:
> Greetings,
>
> This message has been automatically generated in response to the
> creation of a trouble ticket regarding:
> 	"Possible bug - ts -verify -digest, error:ts_rsp_verify.c:291:",
> a summary of which appears below.
>
> There is no need to reply to this message right now.  Your ticket has been
> assigned an ID of [openssl.org #4276].
>
> Please include the string:
>
>           [openssl.org #4276]
>
> in the subject line of all future correspondence about this issue. To do so,
> you may reply to this message.
>
>                          Thank you,
>                          rt@openssl.org
>
> -------------------------------------------------------------------------
>
> Good afternoon Openssl,
>
> please forward this email to whomever it may concern.
>
> I receive an error and the Timestamping provider suspects it is a
> Openssl bug.
> Could you please check if it is openssl or the certificate?
>
>
> This is when the error occurr
> /openssl ts -verify -digest
> e16db7d30581e44a5540f19553852b5a4e4e26f9adc365cc846f94038ee33025 -in
> /tmp/namirial.tsr -CAfile /tmp/NamirialCATSA.pem
> (result:)
> *************
> *Verification: FAILED**
> **140236013643424:error:2F067065:time stamp
> routines:TS_CHECK_SIGNING_CERTS:ess signing certificate
> error:ts_rsp_verify.c:291:*/
>
>
> I attach a complete reproduction scenario. I don't know if it is a
> problem of this TSA certificate or in Openssl due to sha256 digest,
> please help.
>
>
> (in the curl command I cannot provide you the username and password, it
> is a paid service)
>
> Attached are the files resulting from the below commands in sequence and
> the certificate of the TSA, but I'm sure you can check yourself the last
> command where the error occur and  advice.
>
> you can copy and paste the commands below if you're in Linux Ubuntu and
> the files are in the /tmp/ folder
>
> *Reproduction scenario:*
>
> OS: Ubuntu 14.04
> Openssl version: OpenSSL 1.0.1f 6 Jan 2014
>
>
>
> Generate tsq:
> openssl ts -query -digest
> e16db7d30581e44a5540f19553852b5a4e4e26f9adc365cc846f94038ee33025 -sha256
> -cert -out /tmp/namirial.tsq
>
> Readable tsq:
> openssl ts -query -in /tmp/namirial.tsq  -text
> (result:)
> ************
> Hash Algorithm: sha256
> Message data:
>       0000 - e1 6d b7 d3 05 81 e4 4a-55 40 f1 95 53 85 2b 5a .m.....JU@..S.+Z
>       0010 - 4e 4e 26 f9 ad c3 65 cc-84 6f 94 03 8e e3 30 25 NN&...e..o....0%
> Policy OID: unspecified
> Nonce: 0x8CA62B5766A29A8B
> Certificate required: yes
> Extensions:
> ****************
>
>
> Generate tsr (using curl)
> curl -u xxxxxxx:yyyyyy -s --data-binary @/tmp/namirial.tsq -H
> 'Content-Type: application/timestamp-query' -H 'Pragma: no-cache' -H
> 'Accept: application/timestamp-reply' --output /tmp/namirial.tsr
> http://timestamp.firmacerta.it
>
> Readable tsr
> openssl ts -reply -in /tmp/namirial.tsr  -out /tmp/readable_tsr.txt -text
>
> (result:)
> ******************
> Status info:
> Status: Granted.
> Status description: Operation Okay
> Failure info: unspecified
>
> TST info:
> Version: 1
> Policy OID: 1.3.6.1.4.1.36203.2.1
> Hash Algorithm: sha256
> Message data:
>       0000 - e1 6d b7 d3 05 81 e4 4a-55 40 f1 95 53 85 2b 5a .m.....JU@..S.+Z
>       0010 - 4e 4e 26 f9 ad c3 65 cc-84 6f 94 03 8e e3 30 25 NN&...e..o....0%
> Serial number: 0x1947FD96B97A42DE
> Time stamp: Jan 28 14:56:16 2016 GMT
> Accuracy: unspecified seconds, 0x01F4 millis, unspecified micros
> Ordering: no
> Nonce: 0x8CA62B5766A29A8B
> TSA: unspecified
> Extensions:
> ************************
>
>
> Verify
> openssl ts -verify -digest
> e16db7d30581e44a5540f19553852b5a4e4e26f9adc365cc846f94038ee33025 -in
> /tmp/namirial.tsr -CAfile /tmp/NamirialCATSA.pem
> (result:)
> *************
> *Verification: FAILED**
> **140236013643424:error:2F067065:time stamp
> routines:TS_CHECK_SIGNING_CERTS:ess signing certificate
> error:ts_rsp_verify.c:291:*
> ***************
>
>
>

```

From mario.scalabrino@andifyou.com on 2016-02-23 10:34:19:
```
Hello Openssl,

can you please tell me something?
I don't understand if anybody reads this email.

Almost a month has passed.

Mario Scalabrino


Untitled Document On 17/02/2016 14:49, Mario Scalabrino wrote:
> Hello Openssl,
>
> is there any update? Do you need more information?
>
> Thank you
>
> Cheers
>
> Mario Scalabrino
>
> Untitled Document
> *Certify Doc <http://www.certifydoc.eu>* 	
>
> *MARIO SCALABRINO *
>
> Founder & CEO
>
> (+34) 680 128 282
>
> mario.scalabrino@andifyou.com <mailto:mario.scalabrino@andifyou.com>
>
> www.certifydoc.eu <http://www.certifydoc.eu>
>
> Linkedin <https://www.linkedin.com/in/andifyou>Facebook 
> <https://www.facebook.com/certifydoc>Twitter 
> <https://twitter.com/certifydoc>
>
>
> On 28/01/2016 17:16, The default queue via RT wrote:
>> Greetings,
>>
>> This message has been automatically generated in response to the
>> creation of a trouble ticket regarding:
>> 	"Possible bug - ts -verify -digest, error:ts_rsp_verify.c:291:",
>> a summary of which appears below.
>>
>> There is no need to reply to this message right now.  Your ticket has been
>> assigned an ID of [openssl.org #4276].
>>
>> Please include the string:
>>
>>           [openssl.org #4276]
>>
>> in the subject line of all future correspondence about this issue. To do so,
>> you may reply to this message.
>>
>>                          Thank you,
>>                          rt@openssl.org
>>
>> -------------------------------------------------------------------------
>>
>> Good afternoon Openssl,
>>
>> please forward this email to whomever it may concern.
>>
>> I receive an error and the Timestamping provider suspects it is a
>> Openssl bug.
>> Could you please check if it is openssl or the certificate?
>>
>>
>> This is when the error occurr
>> /openssl ts -verify -digest
>> e16db7d30581e44a5540f19553852b5a4e4e26f9adc365cc846f94038ee33025 -in
>> /tmp/namirial.tsr -CAfile /tmp/NamirialCATSA.pem
>> (result:)
>> *************
>> *Verification: FAILED**
>> **140236013643424:error:2F067065:time stamp
>> routines:TS_CHECK_SIGNING_CERTS:ess signing certificate
>> error:ts_rsp_verify.c:291:*/
>>
>>
>> I attach a complete reproduction scenario. I don't know if it is a
>> problem of this TSA certificate or in Openssl due to sha256 digest,
>> please help.
>>
>>
>> (in the curl command I cannot provide you the username and password, it
>> is a paid service)
>>
>> Attached are the files resulting from the below commands in sequence and
>> the certificate of the TSA, but I'm sure you can check yourself the last
>> command where the error occur and  advice.
>>
>> you can copy and paste the commands below if you're in Linux Ubuntu and
>> the files are in the /tmp/ folder
>>
>> *Reproduction scenario:*
>>
>> OS: Ubuntu 14.04
>> Openssl version: OpenSSL 1.0.1f 6 Jan 2014
>>
>>
>>
>> Generate tsq:
>> openssl ts -query -digest
>> e16db7d30581e44a5540f19553852b5a4e4e26f9adc365cc846f94038ee33025 -sha256
>> -cert -out /tmp/namirial.tsq
>>
>> Readable tsq:
>> openssl ts -query -in /tmp/namirial.tsq  -text
>> (result:)
>> ************
>> Hash Algorithm: sha256
>> Message data:
>>       0000 - e1 6d b7 d3 05 81 e4 4a-55 40 f1 95 53 85 2b 5a .m.....JU@..S.+Z
>>       0010 - 4e 4e 26 f9 ad c3 65 cc-84 6f 94 03 8e e3 30 25 NN&...e..o....0%
>> Policy OID: unspecified
>> Nonce: 0x8CA62B5766A29A8B
>> Certificate required: yes
>> Extensions:
>> ****************
>>
>>
>> Generate tsr (using curl)
>> curl -u xxxxxxx:yyyyyy -s --data-binary @/tmp/namirial.tsq -H
>> 'Content-Type: application/timestamp-query' -H 'Pragma: no-cache' -H
>> 'Accept: application/timestamp-reply' --output /tmp/namirial.tsr
>> http://timestamp.firmacerta.it
>>
>> Readable tsr
>> openssl ts -reply -in /tmp/namirial.tsr  -out /tmp/readable_tsr.txt -text
>>
>> (result:)
>> ******************
>> Status info:
>> Status: Granted.
>> Status description: Operation Okay
>> Failure info: unspecified
>>
>> TST info:
>> Version: 1
>> Policy OID: 1.3.6.1.4.1.36203.2.1
>> Hash Algorithm: sha256
>> Message data:
>>       0000 - e1 6d b7 d3 05 81 e4 4a-55 40 f1 95 53 85 2b 5a .m.....JU@..S.+Z
>>       0010 - 4e 4e 26 f9 ad c3 65 cc-84 6f 94 03 8e e3 30 25 NN&...e..o....0%
>> Serial number: 0x1947FD96B97A42DE
>> Time stamp: Jan 28 14:56:16 2016 GMT
>> Accuracy: unspecified seconds, 0x01F4 millis, unspecified micros
>> Ordering: no
>> Nonce: 0x8CA62B5766A29A8B
>> TSA: unspecified
>> Extensions:
>> ************************
>>
>>
>> Verify
>> openssl ts -verify -digest
>> e16db7d30581e44a5540f19553852b5a4e4e26f9adc365cc846f94038ee33025 -in
>> /tmp/namirial.tsr -CAfile /tmp/NamirialCATSA.pem
>> (result:)
>> *************
>> *Verification: FAILED**
>> **140236013643424:error:2F067065:time stamp
>> routines:TS_CHECK_SIGNING_CERTS:ess signing certificate
>> error:ts_rsp_verify.c:291:*
>> ***************
>>
>>
>>
>

```

From rsalz@akamai.com on 2016-03-09 19:10:08:
```
TS is not a high priority for the OpenSSL team.  A month is not a long time.  We are busy right now working on the next release.

```

From mario.scalabrino@andifyou.com on 2016-03-10 08:13:35:
```
do you know anybody who can help? an email or a forum?

SentÂ fromÂ myÂ BlackBerryÂ 10Â smartphone.
Â  Original Message Â 
From: Salz, Rich via RT
Sent: miÃ©rcoles, 9 de marzo de 2016 20:27
To: mario.scalabrino@andifyou.com
Reply To: rt@openssl.org
Cc: openssl-dev@openssl.org
Subject: RE: [openssl-dev] [openssl.org #4276] AutoReply: Possible bug - ts -verify -digest, error:ts_rsp_verify.c:291:

TS is not a high priority for the OpenSSL team. A month is not a long time. We are busy right now working on the next release.


-- 
Ticket here: http://rt.openssl.org/Ticket/Display.html?id=4276
Please log in as guest with password guest if prompted


```

**Comment by MarioScalabrino** [comment]
Hello Rich,
I understand it has been solved, what should I do to test? Upgrade to which version?
I currently run
OS: Ubuntu 14.04
Openssl version: OpenSSL 1.0.1f 6 Jan 2014

Should I upgrade OpenSSL to some specific version or just a patch for "ts" is enough?
Please advice I'm not expert.

**Comment by richsalz** [comment]
Try upgrading to 1.1.0 or 1.0.2 if you must.

**Comment by richsalz** [comment]
no activity, old unsupported release, closing.

**Comment by Gigaju** [comment]
Hi,

I think the bug is still present in OpenSSL 1.1.0.


```
# Distrib info
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

# OpenSSL info
OpenSSL 1.1.0g  2 Nov 2017
built on: reproducible build, date unspecified
platform: debian-amd64
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/x86_64-linux-gnu/engines-1.1\"" 
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
```

Steps to reproduce:
```
# Query generation
$ openssl ts -query -data /etc/passwd -sha256 -out query.tsr

# Here is the query
$ openssl ts -query -text -in query.tsq 
Using configuration from /usr/lib/ssl/openssl.cnf
Version: 1
Hash Algorithm: sha256
Message data:
    0000 - 85 26 8f fc df fc 8f 54-ea d0 04 88 02 35 53 c1   .&.....T.....5S.
    0010 - 06 4b d9 7f 04 ed e4 11-a1 dc 99 12 4c e9 ac 54   .K..........L..T
Policy OID: unspecified
Nonce: 0x985B3170CE7DEED8
Certificate required: no
Extensions:

# Send it to the server - PrimeKey SignServer 4.0.0
$ cat query.tsq | curl -H 'Content-Type: application/timestamp-query' --cacert ca-tls.pem https://signserver.my.domain:8442/signserver/tsa?workerName=TimeStampSigner --data-binary @- -o reply.tsr

# Here is the reply
$ openssl ts -reply -in reply.tsr -text
Using configuration from /usr/lib/ssl/openssl.cnf
Status info:
Status: Granted.
Status description: Operation Okay
Failure info: unspecified

TST info:
Version: 1
Policy OID: [confidential - scrapped]
Hash Algorithm: sha256
Message data:
    0000 - 85 26 8f fc df fc 8f 54-ea d0 04 88 02 35 53 c1   .&.....T.....5S.
    0010 - 06 4b d9 7f 04 ed e4 11-a1 dc 99 12 4c e9 ac 54   .K..........L..T
Serial number: 0x2D26E0730ABDDD1B
Time stamp: Aug 23 14:19:52 2018 GMT
Accuracy: 0x01 seconds, unspecified millis, unspecified micros
Ordering: no
Nonce: 0x985B3170CE7DEED8
TSA: [confidential - scrapped: same info as my TSA cert for sure]
Extensions:

# This is when it gets weird
$ openssl ts -verify -in query.tsr -CAfile tsa-ca.pem -untrusted tsa.pem -queryfile query.tsq 
Using configuration from /usr/lib/ssl/openssl.cnf
Verification: FAILED
140401657303488:error:2F067065:time stamp routines:ts_check_signing_certs:ess signing certificate error:../crypto/ts/ts_rsp_verify.c:230:
```

I can't attach reply ASN.1 for confidentiality issues but if it is really needed I can reproduce these steps in a test environment with no private info and then send the reply.

I attached the query but I don't think it will help.

Could you reopen this issue?

Thanks !

**Comment by mattcaswell** [comment]
I'd suggest opening a new issue. Include the above details and insert a reference to this old issue which was for a different release.
