### ISSUE TITLE
Crash on Windows 11 ARM64 with OpenSSL built in release mode

### ISSUE THREAD

**Issue by equeim** [openssl/openssl#26239]
When OpenSSL is built in release mode for Windows ARM64 (cross-compiling on amd64 host) using MSVC toolchain, the `SSL_CTX_new` function causes program to crash with "Access violation - code c0000005" error. The crash does not occur when OpenSSL is built in debug mode.

OpenSSL is built using `perl Configure no-apps enable-pie no-shared VC-WIN64-ARM` command, test program is:

```
#include <iostream>
#include <openssl/ssl.h>

int main(int argc, char** argv) {
    std::cout << "Entered main\n";
    auto* ctx = SSL_CTX_new(TLS_client_method());
    std::cout << "Created SSL_CTX " << ctx << "\n";
    std::cout << "Exiting main\n";
    return 0;
}
```

This is what WinDbg shows on crash:
```
(1940.d00): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
arm64_crash!ssl_cipher_collect_ciphers+0x34:
00007ff7`02d75fbc a903dff6 stp         x22,x23,[sp,#0x38]
```

Stack trace is:
```
WARNING: Stack pointer is outside the normal stack bounds. Stack unwinding can be inaccurate.
 # Child-SP          RetAddr               Call Site
00 ffffda56`12eff3a0 00000000`00000000     arm64_crash!ssl_cipher_collect_ciphers+0x34 [F:\projects\openssl-3.4.0\ssl\ssl_ciph.c @ 696] 
```

OpenSSL version is 3.4.0, MSVC version is "Microsoft (R) C/C++ Optimizing Compiler Version 19.42.34435 for ARM64".

**Comment by equeim** [comment]
When OpenSSL is built using clang-cl (VC-CLANG-WIN64-CLANGASM-ARM) then it doesn't crash.

**Comment by jamespack** [comment]
Im actually getting the same crash with VC-CLANG-WIN64-CLANGASM-ARM but called from code compiled with VC

**Comment by jamespack** [comment]
Branch `origin/openssl-3.2` seems unaffected by this. FWIW

**Comment by jamespack** [comment]
> Branch `origin/openssl-3.2` seems unaffected by this. FWIW

Notably, I forgot to update the submodules when I checked out 3.2 if thats helpful.

**Comment by jamespack** [comment]
Please ignore both of my comments. I see now. Its the debug build that is not affected. Both ARM configs were affected for me.

**Comment by jamespack** [comment]
Defining `-DNO_INTERLOCKEDOR64` in the `CLFAGS` works around it for me for anybody that lands here looking for a solution until the maintainers can get something landed. It kind of looks like this is the only intrinsic that hasn't been replaced?

**Comment by nhorman** [comment]
please see https://github.com/openssl/openssl/issues/26258#issuecomment-2562487830
It appears that clang doesn't fully support MSVC intrinsics:
https://clang.llvm.org/docs/MSVCCompatibility.html

Adding NO_INTERLOCKEDOR64 as a define in threads_win.c when building with clang seems like the right solution to me

**Comment by ConnorBP** [comment]
I believe that this is caused by SSL_CTX_new returning NULL with no error code. I am getting this on my machine as well

**Comment by ConnorBP** [comment]
> When OpenSSL is built using clang-cl (VC-CLANG-WIN64-CLANGASM-ARM) then it doesn't crash.

Sadly this did not fix my crash when using this build configuration:

```
// Open 64 bit developer command prompt as admin
set CFLAGS=-DNO_INTERLOCKEDOR64
perl Configure no-apps enable-pie no-shared -DNO_INTERLOCKEDOR64
nmake
nmake test
nmake install
```

The strangest thing is that the program runs fine when it is an EXE but if I utilize the same code in dll form it crashes with this error (perhaps due to threading?).

**Comment by Nick7K** [comment]
I can confirm that set CFLAGS=-DNO_INTERLOCKEDOR64 doesn't work here either.

**Comment by Nick7K** [comment]
Possibly a useful update and may help for fixing the issue.

Building OpenSSL on an ARM64 laptop and using the binaries resolves the issue, at least here.

**Comment by heweisheng** [comment]
I am crash too! when I use libcurl with openssl in windows 11 on arm64

**Comment by Nick7K** [comment]
Has anyone found a solution/fix for this?

**Comment by jamespack** [comment]
> Has anyone found a solution/fix for this?

DNO_INTERLOCKEDOR64 worked for me on windows ARM64

**Comment by Nick7K** [comment]
> > Has anyone found a solution/fix for this?
> 
> DNO_INTERLOCKEDOR64 worked for me on windows ARM64

How did you set that? When I tried, it dodn't help here.

**Comment by jamespack** [comment]
> > > Has anyone found a solution/fix for this?
> > 
> > DNO_INTERLOCKEDOR64 worked for me on windows ARM64
> 
> How did you set that? When I tried, it didn't help here.

Environment variable CFLAGS

https://github.com/openssl/openssl/blob/master/Configure

Make sure to `nmake clean`

And reconfigure and rebuild

**Comment by jamespack** [comment]
Clean is important. A simple rebuild won't do it I don't think

**Comment by Nick7K** [comment]
> Environment variable `CFLAGS=-DNO_INTERLOCKEDOR64`
> 
> https://github.com/openssl/openssl/blob/master/Configure
> 
> Make sure to `nmake clean`
> 
> And reconfigure and rebuild

Thank you. 

Unfortunately, it still doesn't work here. I have even tried to completely remove vcpkg and its archive.

I have tried both modifying the triplet with

set(VCPKG_C_FLAGS "-DNO_INTERLOCKEDOR64")

and setting the environment variable at the command line

set(VCPKG_C_FLAGS "-DNO_INTERLOCKEDOR64")

**Comment by jamespack** [comment]
It would just be a regular old environment variable CFLAGS no?

**Comment by jamespack** [comment]
> > Environment variable `CFLAGS=-DNO_INTERLOCKEDOR64`
> > 
> > https://github.com/openssl/openssl/blob/master/Configure
> > 
> > Make sure to `nmake clean`
> > 
> > And reconfigure and rebuild
> 
> Thank you. 
> 
> Unfortunately, it still doesn't work here. I have even tried to completely remove vcpkg and its archive.
> 
> I have tried both modifying the triplet with
> 
> set(VCPKG_C_FLAGS "-DNO_INTERLOCKEDOR64")
> 
> and setting the environment variable at the command line
> 
> set(VCPKG_C_FLAGS "-DNO_INTERLOCKEDOR64")

If you're building with vcpkg you may have to ask them to implement the patch. Or you could checkout the source code and build it yourself.

**Comment by gietal-msft** [comment]
CFLAGS=-DNO_INTERLOCKEDOR64 did not fix it for me, but **removing /O2 flag did fix the crash for me**. 
In fact adding any optimization flags (/Ox /O1 /O2) seems to cause the crash on arm64 windows

**Comment by jamespack** [comment]
Nice

**Comment by jamespack** [comment]
How are you building? From source? Or some other method?

**Comment by gietal-msft** [comment]
from source

**Comment by Nick7K** [comment]
> How are you building? From repository source or vcpkg or something else?

If it helps, we use vcpkg. This does resolve the issue, but we have only checked with the /Od disabled flag. O1, O2 etc all cause the issue.

We didn't try the various /Ox options [https://learn.microsoft.com/en-us/cpp/build/reference/o-options-optimize-code?view=msvc-170](url).

**Comment by rozmansi** [comment]
Building with Visual Studio 2019 produces working OpenSSL ARM64 binaries.

**Comment by jamespack** [comment]
> from source

Building from repo source with repo provided build tools and defining the flag I said is what worked for me. But my use case is limited.

**Comment by thierryba** [comment]
I am seeing the same problem and passing CFLAGS=-DNO_INTERLOCKEDOR64 did fix it for me.

**Comment by hchhapar** [comment]
I am also able to reproduce this issue on visual studio 2022. It only works if we remove /02 flag. Is there any other optimization we can use or how we can escalate this issue to Microsoft?

**Comment by thierryba** [comment]
@hchhapar I have reported the problem to MS and they asked for exact step for reproduction. Maybe you guys who are  interested could vote on that issue (link above) ?

**Comment by hchhapar** [comment]
@thierryba sure, i can put together the reproduction, VS 2022 (cl,etc.) toolchain versions which is causing this issue, along with build instructions.

**Comment by thierryba** [comment]
@hchhapar I have detailed the steps in https://developercommunity.visualstudio.com/t/Openssl-crashes-on-arm64-when-built-with/10896571 
Can you open that content (aka is it public)?

**Comment by hchhapar** [comment]
@thierryba i replied publically on that content and some more info on my finding with different VS2022 versions.

**Comment by thierryba** [comment]
It is supposedly fixed in VS 17.14 that just got released. Anyone can confirm ?

**Comment by jnarang75** [comment]
On utilizing VS 17.14 which is in preview I am able to see this crash issue gets fixed

**Comment by thierryba** [comment]
VS 17.14 was actually released a few hours ago and is not in preview any more

**Comment by Nick7K** [comment]
Yes, it is fixed here. This may be the relevant update.

[https://devblogs.microsoft.com/cppblog/introducing-the-forceinterlockedfunctions-switch-for-arm64/?ocid=cppblog_eml_tnp_autoid125_readmore](url)

**Comment by thierryba** [comment]
@equeim so this ticket should probably be closed, right?

**Comment by jnarang75** [comment]
right

**Comment by rozmansi** [comment]
Using Visual Studio 17.14.0, OpenSSL no longer rises "Access violation - code c0000005". Definitely a progress. Unfortunately, the TLS still doesn't handshake while the same code compiled for x64 does.

**Comment by thierryba** [comment]
@rozmansi I just tried openssl s_client -connect google.com

and that thing succeeds for me. How does it work for you?

**Comment by rozmansi** [comment]
> [@rozmansi](https://github.com/rozmansi) I just tried openssl s_client -connect google.com
> 
> and that thing succeeds for me. How does it work for you?

I apologize for late reply. Been away on other projects.

Here: if I compile this https://codeberg.org/Amebis/OpenVPN/src/branch/release/2.5 OpenVPN branch using Visual Studio 2022 17.14.1, the C0000005 crash no longer appears on attempt to establish VPN connection. However, after initial TLS packet the connection is dropped. CA chain is not validated:
```
2025-05-23 12:07:27 us=156000 TLS: Initial packet from [AF_INET]145.100.181.181:1194, sid=c783f2cf 7374fc20
2025-05-23 12:07:27 us=156000 write_control_auth(): P_ACK_V1
2025-05-23 12:07:27 us=156000  event_wait returned 2
2025-05-23 12:07:27 us=156000 UDP WRITE [62] to [AF_INET]145.100.181.181:1194: P_ACK_V1 kid=0 sid=408e99c2 73780425 [ ]
2025-05-23 12:07:27 us=156000 UDP write returned 62
2025-05-23 12:07:27 us=156000 write_control_auth(): P_CONTROL_V1
2025-05-23 12:07:27 us=156000  event_wait returned 1
2025-05-23 12:07:27 us=156000 UDP WRITE [1116] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=408e99c2 73780425 [ ] pid=872 DATA 3048df47 a6bd9b2b 759fec61 7ea3fe0d d6634a3d 1eb84eef 0facc0ba 38fd27e[more...]
2025-05-23 12:07:27 us=156000 UDP write returned 1116
2025-05-23 12:07:27 us=156000 write_control_auth(): P_CONTROL_V1
2025-05-23 12:07:27 us=156000  event_wait returned 1
2025-05-23 12:07:27 us=156000 UDP WRITE [439] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=408e99c2 73780425 [ ] pid=1128 DATA 3048df99 1b4830fe 3c1ea53e 0725136d 1967e0b4 7e08eb6e 0a847c0a a7bffb2[more...]
2025-05-23 12:07:27 us=156000 UDP write returned 439
2025-05-23 12:07:28 us=250000  event_wait returned 0
2025-05-23 12:07:29 us=328000  event_wait returned 0
2025-05-23 12:07:29 us=328000 write_control_auth(): P_CONTROL_V1
2025-05-23 12:07:29 us=328000  event_wait returned 1
2025-05-23 12:07:29 us=328000 UDP WRITE [1116] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=408e99c2 73780425 [ ] pid=1384 DATA 3048df9e 21fc0ce0 c5117dda a180045f a5e43649 741ce2a5 d2ca0f10 458f7cd[more...]
2025-05-23 12:07:29 us=328000 UDP write returned 1116
2025-05-23 12:07:29 us=328000 write_control_auth(): P_CONTROL_V1
2025-05-23 12:07:29 us=328000  event_wait returned 1
2025-05-23 12:07:29 us=328000 UDP WRITE [439] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=408e99c2 73780425 [ ] pid=1640 DATA 3048df2c c5c8fef4 2b4f8914 9d393dfa bc857c95 7137e692 afd9758a 1d6bea1[more...]
2025-05-23 12:07:29 us=328000 UDP write returned 439
2025-05-23 12:07:30 us=421000  event_wait returned 0
2025-05-23 12:07:31 us=500000  event_wait returned 0
2025-05-23 12:07:32 us=593000  event_wait returned 0
2025-05-23 12:07:33 us=671000  event_wait returned 0
2025-05-23 12:07:33 us=671000 write_control_auth(): P_CONTROL_V1
2025-05-23 12:07:33 us=671000  event_wait returned 1
2025-05-23 12:07:33 us=671000 UDP WRITE [1116] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=408e99c2 73780425 [ ] pid=1896 DATA 3048df42 eed8a868 10edbc1f 6fd74e4d 68918b53 52a3b1c1 9b8e6747 130ca07[more...]
2025-05-23 12:07:33 us=671000 UDP write returned 1116
2025-05-23 12:07:33 us=671000 write_control_auth(): P_CONTROL_V1
2025-05-23 12:07:33 us=671000  event_wait returned 2
2025-05-23 12:07:33 us=671000 UDP WRITE [439] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=408e99c2 73780425 [ ] pid=2152 DATA 3048dfc3 e356ac25 380dd037 4545c9e0 c629941b a55a41aa a6ea2a18 fab72c9[more...]
2025-05-23 12:07:33 us=671000 UDP write returned 439
2025-05-23 12:07:34 us=765000  event_wait returned 0
2025-05-23 12:07:35 us=843000  event_wait returned 0
2025-05-23 12:07:36 us=937000  event_wait returned 0
2025-05-23 12:07:38 us=15000  event_wait returned 0
2025-05-23 12:07:39 us=171000  event_wait returned 0
2025-05-23 12:07:40 us=328000  event_wait returned 0
2025-05-23 12:07:41 us=484000  event_wait returned 0
2025-05-23 12:07:41 us=484000 write_control_auth(): P_CONTROL_V1
2025-05-23 12:07:41 us=484000  event_wait returned 1
2025-05-23 12:07:41 us=484000 UDP WRITE [1116] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=408e99c2 73780425 [ ] pid=2408 DATA 3048dff5 9b7fe736 0ac95ba8 e223ab5c 11de9c22 25be332a d3ec8e90 9d18cfc[more...]
2025-05-23 12:07:41 us=484000 UDP write returned 1116
2025-05-23 12:07:41 us=484000 write_control_auth(): P_CONTROL_V1
2025-05-23 12:07:41 us=484000  event_wait returned 2
2025-05-23 12:07:41 us=484000 UDP WRITE [439] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=408e99c2 73780425 [ ] pid=2664 DATA 3048df98 c8776457 f89a33ca bb5d2212 fde438ba 01bf566b 3e21e027 cceb683[more...]
2025-05-23 12:07:41 us=484000 UDP write returned 439
2025-05-23 12:07:42 us=640000  event_wait returned 0
2025-05-23 12:07:43 us=812000  event_wait returned 0
2025-05-23 12:07:44 us=953000  event_wait returned 0
2025-05-23 12:07:46 us=125000  event_wait returned 0
2025-05-23 12:07:47 us=281000  event_wait returned 0
2025-05-23 12:07:48 us=437000  event_wait returned 0
2025-05-23 12:07:49 us=640000  event_wait returned 0
2025-05-23 12:07:50 us=875000  event_wait returned 0
2025-05-23 12:07:52 us=78000  event_wait returned 0
2025-05-23 12:07:53 us=296000  event_wait returned 0
2025-05-23 12:07:54 us=500000  event_wait returned 0
2025-05-23 12:07:55 us=734000  event_wait returned 0
2025-05-23 12:07:56 us=953000  event_wait returned 0
2025-05-23 12:07:58 us=171000  event_wait returned 0
2025-05-23 12:07:58 us=171000 write_control_auth(): P_CONTROL_V1
2025-05-23 12:07:58 us=171000  event_wait returned 1
2025-05-23 12:07:58 us=171000 UDP WRITE [1116] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=408e99c2 73780425 [ ] pid=2920 DATA 3048df68 1d7f8ce8 3e3236e0 50055b2f aec46e5b 66b45c99 30318159 af1b239[more...]
2025-05-23 12:07:58 us=171000 UDP write returned 1116
2025-05-23 12:07:58 us=171000 write_control_auth(): P_CONTROL_V1
2025-05-23 12:07:58 us=171000  event_wait returned 2
2025-05-23 12:07:58 us=171000 UDP WRITE [439] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=408e99c2 73780425 [ ] pid=3176 DATA 3048df08 b7712679 c86434cf b7faf8d6 78731b88 3f4bcc12 9310e7eb 29ea020[more...]
2025-05-23 12:07:58 us=171000 UDP write returned 439
2025-05-23 12:07:59 us=265000  event_wait returned 0
2025-05-23 12:08:00 us=359000  event_wait returned 0
2025-05-23 12:08:01 us=437000  event_wait returned 0
2025-05-23 12:08:02 us=546000  event_wait returned 0
2025-05-23 12:08:03 us=625000  event_wait returned 0
2025-05-23 12:08:04 us=718000  event_wait returned 0
2025-05-23 12:08:05 us=828000  event_wait returned 0
2025-05-23 12:08:06 us=921000  event_wait returned 0
2025-05-23 12:08:08  event_wait returned 0
2025-05-23 12:08:09 us=203000  event_wait returned 0
2025-05-23 12:08:10 us=390000  event_wait returned 0
2025-05-23 12:08:11 us=578000  event_wait returned 0
2025-05-23 12:08:12 us=765000  event_wait returned 0
2025-05-23 12:08:13 us=953000  event_wait returned 0
2025-05-23 12:08:15 us=140000  event_wait returned 0
2025-05-23 12:08:16 us=328000  event_wait returned 0
2025-05-23 12:08:17 us=515000  event_wait returned 0
2025-05-23 12:08:18 us=687000  event_wait returned 0
2025-05-23 12:08:19 us=875000  event_wait returned 0
2025-05-23 12:08:21 us=15000  event_wait returned 0
2025-05-23 12:08:22 us=140000  event_wait returned 0
2025-05-23 12:08:23 us=265000  event_wait returned 0
2025-05-23 12:08:24 us=390000  event_wait returned 0
2025-05-23 12:08:25 us=531000  event_wait returned 0
2025-05-23 12:08:26 us=656000  event_wait returned 0
2025-05-23 12:08:27 us=781000  event_wait returned 0
2025-05-23 12:08:27 us=781000 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
2025-05-23 12:08:27 us=781000 TLS Error: TLS handshake failed
```

When running binaries of the same branch compiled using Visual Studio 2019 16.11.46, it connects. TLS handshake succeeds, CA chain is validated:
```
2025-05-23 11:31:38 us=875000 TLS: Initial packet from [AF_INET]145.100.181.181:1194, sid=f024cc1e 70e3dd54
2025-05-23 11:31:38 us=875000 write_control_auth(): P_ACK_V1
2025-05-23 11:31:38 us=875000  event_wait returned 2
2025-05-23 11:31:38 us=875000 UDP WRITE [62] to [AF_INET]145.100.181.181:1194: P_ACK_V1 kid=0 sid=6e72ff24 081ff746 [ ]
2025-05-23 11:31:38 us=875000 UDP write returned 62
2025-05-23 11:31:38 us=875000 write_control_auth(): P_CONTROL_V1
2025-05-23 11:31:38 us=875000  event_wait returned 1
2025-05-23 11:31:38 us=875000 UDP WRITE [1116] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=6e72ff24 081ff746 [ ] pid=872 DATA 30407ada 63e7aca6 d273e206 056c50f0 e6b6f879 26db5b35 7c241269 b32ca99[more...]
2025-05-23 11:31:38 us=875000 UDP write returned 1116
2025-05-23 11:31:38 us=875000 write_control_auth(): P_CONTROL_V1
2025-05-23 11:31:38 us=875000  event_wait returned 1
2025-05-23 11:31:38 us=875000 UDP WRITE [439] to [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=6e72ff24 081ff746 [ ] pid=1128 DATA 30407a1e f60cc98a 3b51a9e1 17c18655 89582d00 c55dd3e9 4392c235 21717f2[more...]
2025-05-23 11:31:38 us=875000 UDP write returned 439
2025-05-23 11:31:38 us=906000  event_wait returned 1
2025-05-23 11:31:38 us=906000 UDP read returned 62
2025-05-23 11:31:38 us=906000 UDP READ [62] from [AF_INET]145.100.181.181:1194: P_ACK_V1 kid=0 sid=f024cc1e 70e3dd54 [ ]
2025-05-23 11:31:38 us=906000  event_wait returned 1
2025-05-23 11:31:38 us=906000 UDP read returned 1186
2025-05-23 11:31:38 us=906000 UDP READ [1186] from [AF_INET]145.100.181.181:1194: P_CONTROL_V1 kid=0 sid=f024cc1e 70e3dd54 [ ] pid=872 DATA 30407ed7 d606ce95 8aad7de7 eebc4830 ea9befc0 7ff18b0f e91e694a 3d420d0[more...]
2025-05-23 11:31:38 us=921000 VERIFY OK: depth=1, CN=VPN CA
2025-05-23 11:31:38 us=921000 VERIFY KU OK
2025-05-23 11:31:38 us=921000 Validating certificate extended key usage
2025-05-23 11:31:38 us=921000 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2025-05-23 11:31:38 us=921000 VERIFY EKU OK
```

**Comment by cron2** [comment]
@rozmansi do you recompile everything, or just openvpn/just openssl?

On the failing attempt, is there anything interesting in the server logs?  (It seems as if the server is just not responding at all, after the first packet, which hints at "corrupted TLS packets")

**Comment by rozmansi** [comment]
> [@rozmansi](https://github.com/rozmansi) do you recompile everything, or just openvpn/just openssl?

Everything is recompiled IMHO:
I'm using a separate PC with Visual Studio 2019 installed.
On that PC in vcpkg folder, I do `git clean`, `git pull`, `bootstrap-vcpkg` and `rd /s "%LOCALAPPDATA%\vcpkg\archives"`.
The working folder of the https://codeberg.org/Amebis/OpenVPN/src/branch/release/2.5 repository is cleaned using `git clean` before building.
Testing Release builds.

> On the failing attempt, is there anything interesting in the server logs? (It seems as if the server is just not responding at all, after the first packet, which hints at "corrupted TLS packets")

I don't have access to server (logs). 🤷‍♂️ Will attempt to get somebody on the server side to deliver the logs.
Indeed, it feels like server is not happy with the initial TLS packet and drops it.

Another note, the problem is 100% repeatable.

**Comment by thierryba** [comment]
I have a totally different stack. I am using Qt (with QtNetwork using the openssl backend). And with the latest VC on arm64 it just works for me.

**Comment by equeim** [comment]
It doesn't crash for me anymore either.

@rozmansi I suggest you open a separate issue since it's not a crash anymore

**Comment by Fedr** [comment]
We hit a crash with this same signature on Windows ARM64 — `/O2`-only, and cdb's "stack pointer is outside the normal stack bounds" — but at a different site: `tls_parse_all_extensions` (`ssl/statem/extensions.c:747`) while parsing a TLS 1.3 ServerHello, in OpenSSL 3.6.3 with MSVC 19.51.36256.

Tracking it down, the cause turned out to be a code-generation defect rather than anything in OpenSSL. At `/O2 /Gs0` the compiler emits:

```
0000: sub  sp,sp,#0x60
0004: mov  x15,#1
0008: bl   __chkstk          ; bl overwrites lr
000C: sub  sp,sp,x15,lsl #4
0010: ldr  x8,[x0,#0x878]
  ...
0038: str  x30,[sp,#0x60]    ; spills x30, already destroyed at 0x08
```

`bl __chkstk` destroys the link register before the prologue spills it, so the value stored and reloaded by every `ret` path is `tls_parse_all_extensions+0xc` — the function returns into its own prologue. There `sub sp,sp,x15,lsl #4` re-runs with the body's leftover `x15` and throws `sp` outside the thread stack (hence the warning), and the next instruction reads `[x0+0x878]` where `x0` is now the function's own return value, `1`, giving an access violation at `0x879`.

`/Gs0` matters here because OpenSSL's own `VC-WIN64-ARM` configuration passes it, which is what makes a `__chkstk` call appear in this frame at all. Rebuilding OpenSSL with `--release -O1` or `--release -Od`, everything else unchanged, produces a correct prologue and a working handshake.

Reduced to ~25 lines of ordinary C and reported to Microsoft:

- https://developercommunity.visualstudio.com/t/ARM64-O2-Gs0:-prologue-calls-__chks/11146442
- Live on Compiler Explorer (`vcpp_v19_51_VS18_6_arm64`, `/O2 /Gs0`): https://gcc.godbolt.org/z/jh75KW4dq

Since this issue was closed on the basis that VS 17.14 fixed the earlier instance, it may be worth noting that the same class of defect is still present in 19.51 — though ours is a different function, so I can't claim it is literally the same bug.
