### ISSUE TITLE
EVP_CTRL_AEAD_SET_TAG fails for OCB

### ISSUE THREAD

**Issue by jorangreef** [openssl/openssl#8331]
When **decrypting** using OCB mode, setting a custom tag size fails unless `EVP_CTRL_AEAD_SET_TAG` is called twice (first with `NULL`, and then the second time with the actual tag buffer).

This fails unexpectedly when **decrypting**:
```c
assert(EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_TAG, tag_size, tag));
```

This succeeds when **decrypting**:
```c
assert(EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_TAG, tag_size, NULL));
assert(EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_TAG, tag_size, tag));
```

The documentation indicates that this double call should only be necessary when **encrypting**, not when **decrypting**:

> In OCB mode, calling this before encryption with tag set to NULL sets
the tag length. If this is not called prior to encryption, a default tag
length is used.

I think this is probably a bug?

**Comment by mattcaswell** [comment]
Yes - looks like a bug to me.

**Comment by erbsland-dev** [comment]
@mattcaswell When I read this test correctly, all `OCB` tests run successfully by calling `EVP_CTRL_AEAD_SET_TAG` with the tag set in the first call.

https://github.com/openssl/openssl/blob/a4fd94851261c55f9ad020bf22d4f29bda0b58be/test/evp_test.c#L1101-L1112

https://github.com/openssl/openssl/blob/a4fd94851261c55f9ad020bf22d4f29bda0b58be/test/evp_test.c#L1276-L1283

For me, it seems this issue was resolved, otherwise one of the test would fail.

**Comment by bukka** [comment]
I haven't tested it yeat but from reading this test the second condition is there exactly to run OCB test second time. Firstly it's called in https://github.com/openssl/openssl/blob/a4fd94851261c55f9ad020bf22d4f29bda0b58be/test/evp_test.c#L1108-L1112 for all AEAD modes except GCM when tag is not set (setting length is not needed for GCM) and then in the linked code to actually run second time just for OCB. So it does not seem fixed to me unless I missed anything (which is quite possible :) )?

**Comment by erbsland-dev** [comment]
@bukka Thank you for your feedback on the OCB test scenario. To ensure this can be properly addressed, could you please provide a minimal example code that demonstrates the issue still exists?

I’ve attempted various ways to reproduce it using the existing tests but haven’t found any code paths where this problem occurs. If there is one, I would be happy to fix the issue correctly.

**Comment by bukka** [comment]
You could try to remove the condition that [you linked](https://github.com/openssl/openssl/blob/a4fd94851261c55f9ad020bf22d4f29bda0b58be/test/evp_test.c#L1276-L1283) from the test and see if the test still works. We had issue with this when integrating to PHP which was fixed here: https://github.com/php/php-src/pull/6337 but it was during 1.1 time. If you can't recreate with that test change, I will try to find some time next week to see if I still manage to recreate it.

**Comment by t8m** [comment]
Hmm... by code inspection I see this bug is still there. However do we really want to change it? I would instead change the documentation to drop `when encrypting` from this paragraph:
```
In OCB mode, calling this when encrypting with C<tag> set to C<NULL> sets the
tag length. The tag length can only be set before specifying an IV. If this is
not called prior to setting the IV during encryption, then a default tag length
is used.
```

IMO it is a good preventive measure against accidentally changing the tag length during the decryption.

**Comment by bukka** [comment]
Yeah 16 is default so think it doesn't require extra setting.

I wouldn't consider this as a bug but more as a bit suprising API requirement which could be just fixed using docs. I'd think it's a more feature request to make the behavior more consistent between AEAD modes. I haven't checked if there is some technical reason why it needs to be like that though.
