### ISSUE TITLE
How to use openssl generate sm2 request file, the purpose is to generate sm2 double certificate by requesting file

### ISSUE THREAD

**Issue by ygm521** [openssl/openssl#8975]

**Comment by InfoHunter** [comment]
It's not supported yet in current OpenSSL.

**Comment by InfoHunter** [comment]
@ygm521 , I opened a new PR on supporting SM2 certificate signing, which can resolve your issue on SM2 CSR.

**Comment by ygm521** [comment]
openssl not support ECC-SM4-SM3 Cryptographic kit。

**Comment by InfoHunter** [comment]
That is one CTLS ciphersuite, OpenSSL has not plan to support that yet.

**Comment by ygm521** [comment]
@InfoHunter How can I remove the SET reserved printablestring?
![req](https://user-images.githubusercontent.com/7271089/69120281-306cc280-0ad4-11ea-8430-27805d0f47f5.png)

**Comment by mattcaswell** [comment]
This was fixed by PR #9085. Closing.

**Comment by ygm521** [comment]
@mattcaswell not fixed！

**Comment by mattcaswell** [comment]
> @mattcaswell not fixed！

I assume this is now captured in #10472?

**Comment by ygm521** [comment]
@mattcaswell not fixed! why closed?
https://github.com/openssl/openssl/issues/10472

**Comment by mattcaswell** [comment]
I'm asking whether #10472 covers the same issue? If it does then there is no need for this one to be open too.

**Comment by InfoHunter** [comment]
> I'm asking whether #10472 covers the same issue? If it does then there is no need for this one to be open too.

It covers. And #9085 added the SM2 certificate signing ability into OpenSSL, so there is no problem to close this one and let's focusing on #10472 

*Note: we are still not sure if this is a bug or just interoperability issues between different implementations for unclear specifications - need to investigate on this...*

**Comment by ygm521** [comment]
@mattcaswell I am agree @InfoHunter .
